# tests/testthat/test-e2e-rnaseq.R
#
# End-to-end regression test: run the RNA-seq pipeline for real via tar_make()
# and assert the DE result. Because the repo's shipped RNA example is a 5-gene
# toy (too small for DESeq2), the input is a seeded synthetic count matrix
# generated by the helper. Heavy + opt-in: set RUN_E2E_OMICS=1 (and
# RUN_E2E_OMICS_FULL=1 for the file-output checks). Scaffolding: helper-e2e.R.

RNA_STAGE  <- e2e_stage_rna(seed = 1L)
RNA_CONFIG <- "e2e_rnaseq_config.yaml"

test_that("rnaseq runs end-to-end and produces a well-formed DE result", {
  if (!e2e_should_run()) skip("Set RUN_E2E_OMICS=1 to run the heavy end-to-end omic tests.")
  skip_if_not_installed("DESeq2")
  skip_if_not_installed("edgeR")

  res <- run_omic_e2e(RNA_CONFIG, RNA_STAGE, "rna_de_res")
  de  <- res$values[["rna_de_res"]]

  # --- structure: the DE contract holds ---
  expect_true(is.list(de))
  expect_error(assert_de_contract(de, stage = "rna"), NA)
  expect_s3_class(de$summary_df, "data.frame")
  expect_gt(nrow(de$summary_df), 0)
  expect_true("pass_any_contrast" %in% names(de$summary_df))
  expect_length(de$de_tables, 1L)   # exactly the one configured contrast

  # --- numbers: significant count in a sane band ---
  # The generator injects strong (~4x) DE into GENE_0001..GENE_0040 (of 300).
  # Wide band; tighten after the first green run.
  sig <- e2e_significant_ids(de$summary_df)
  expect_gte(length(sig), 10L)
  expect_lte(length(sig), 200L)
})

test_that("rnaseq DE is reproducible across runs (same seed)", {
  if (!e2e_should_run()) skip("Set RUN_E2E_OMICS=1 to run the heavy end-to-end omic tests.")
  skip_if_not_installed("DESeq2")
  skip_if_not_installed("edgeR")

  r1 <- run_omic_e2e(RNA_CONFIG, RNA_STAGE, "rna_de_res")
  r2 <- run_omic_e2e(RNA_CONFIG, RNA_STAGE, "rna_de_res")

  expect_identical(
    sort(e2e_significant_ids(r1$values[["rna_de_res"]]$summary_df)),
    sort(e2e_significant_ids(r2$values[["rna_de_res"]]$summary_df))
  )
})

test_that("rnaseq writes legacy output files (full run)", {
  if (!e2e_should_run_full()) skip("Set RUN_E2E_OMICS_FULL=1 to run the heavier file-output checks.")
  skip_if_not_installed("DESeq2")
  skip_if_not_installed("edgeR")
  skip_if_not_installed("openxlsx")

  res   <- run_omic_e2e(RNA_CONFIG, RNA_STAGE, "rna_outputs_legacy")
  files <- list.files(res$out_dir, recursive = TRUE, full.names = TRUE)

  xlsx <- files[grepl("\\.xlsx$", files)]
  expect_gte(length(xlsx), 1L)
  expect_true(all(file.size(xlsx) > 0))
})
