# tests/testthat/test-e2e-rnaseq.R
#
# End-to-end regression test: run the RNA-seq pipeline for real via tar_make()
# and assert the DE result. Because the repo's shipped RNA example is a 5-gene
# toy (too small for DESeq2), the input is a seeded synthetic count matrix
# generated by the helper. Heavy + opt-in: set RUN_E2E_OMICS=1 (and
# RUN_E2E_OMICS_FULL=1 for the file-output checks). Scaffolding: helper-e2e.R.
#
# Contract note: rna_de_res == mod_rnaseq_de() == run_deseq2_de(), which returns
# list(dds, tables) — per-contrast DESeq2 tables, NOT a summary_df. The
# significance summary (FeatureID + pass_any_contrast) is built here via the
# pipeline's own build_rnaseq_summary_df(), the same function the downstream
# targets use.

RNA_STAGE  <- e2e_stage_rna(seed = 1L)
RNA_CONFIG <- "e2e_rnaseq_config.yaml"
RNA_TRUTH  <- sprintf("GENE_%04d", 1:40)   # generator injects strong DE here

test_that("rnaseq runs end-to-end and recovers the injected DE signal", {
  if (!e2e_should_run()) skip("Set RUN_E2E_OMICS=1 to run the heavy end-to-end omic tests.")
  skip_if_not_installed("DESeq2")
  skip_if_not_installed("edgeR")

  res <- run_omic_e2e(RNA_CONFIG, RNA_STAGE, "rna_de_res")
  de  <- res$values[["rna_de_res"]]

  # --- structure: DESeq2 result shape ---
  expect_true(is.list(de))
  expect_true(!is.null(de$tables))
  expect_length(de$tables, 1L)                 # exactly the one configured contrast
  tab <- de$tables[[1]]
  expect_s3_class(tab, "data.frame")
  expect_true(all(c("FeatureID", "log2FoldChange", "pvalue", "padj") %in% names(tab)))

  # Build the significance summary the same way the pipeline does.
  summ <- build_rnaseq_summary_df(de$tables, res$config$modes$rna$de)
  expect_true(all(c("FeatureID", "pass_any_contrast") %in% names(summ)))
  expect_gt(nrow(summ), 0)

  # --- numbers: significant count in a sane band + injected signal recovered ---
  # Wide band; tighten to a snug range after the first green run.
  sig <- e2e_significant_ids(summ)
  expect_gte(length(sig), 10L)
  expect_lte(length(sig), 200L)

  # The injected truth genes must be present in the tested universe, and the
  # majority of them recovered among the significant hits (guards against
  # ID-alignment / contrast-direction / selection regressions).
  expect_true(any(RNA_TRUTH %in% summ$FeatureID))
  recall <- mean(RNA_TRUTH %in% sig)
  expect_gte(recall, 0.5)
})

test_that("rnaseq DE is reproducible across runs (same seed)", {
  if (!e2e_should_run()) skip("Set RUN_E2E_OMICS=1 to run the heavy end-to-end omic tests.")
  skip_if_not_installed("DESeq2")
  skip_if_not_installed("edgeR")

  r1 <- run_omic_e2e(RNA_CONFIG, RNA_STAGE, "rna_de_res")
  r2 <- run_omic_e2e(RNA_CONFIG, RNA_STAGE, "rna_de_res")

  s1 <- e2e_significant_ids(build_rnaseq_summary_df(r1$values[["rna_de_res"]]$tables,
                                                    r1$config$modes$rna$de))
  s2 <- e2e_significant_ids(build_rnaseq_summary_df(r2$values[["rna_de_res"]]$tables,
                                                    r2$config$modes$rna$de))
  expect_identical(sort(s1), sort(s2))
})

test_that("rnaseq writes legacy output files (full run)", {
  if (!e2e_should_run_full()) skip("Set RUN_E2E_OMICS_FULL=1 to run the heavier file-output checks.")
  skip_if_not_installed("DESeq2")
  skip_if_not_installed("edgeR")
  skip_if_not_installed("openxlsx")

  res   <- run_omic_e2e(RNA_CONFIG, RNA_STAGE, "rna_outputs_legacy")
  files <- list.files(res$out_dir, recursive = TRUE, full.names = TRUE)

  xlsx <- files[grepl("\\.xlsx$", files)]
  expect_gte(length(xlsx), 1L)
  expect_true(all(file.size(xlsx) > 0))
})
