# R/domain/lipidomics/11_powerpoint.R
#
# Generate a PowerPoint presentation summarizing lipidomics pipeline results.
# Each slide includes an AI-generated bottom line via Claude Code CLI,
# following the same pattern as 10_pipeline_summary.R and 12_commentary.R.
#
# Requires: officer, flextable (optional, for tables)
# Depends:  R/core/16_pptx_helpers.R (all PPTX_* constants, pptx_fp_*, pptx_add_*)


# ==============================================================================
# POWERPOINT GENERATION
# ==============================================================================

#' Generate a lipidomics summary PowerPoint
#'
#' @param pre             Preprocessed data list.
#' @param qc_res          QC results list (with $plots and $files).
#' @param de_res          DE results list (with $summary_df, $de_tables).
#' @param feature_sel_res Feature selection results (rf, plsda) or NULL.
#' @param class_res       Lipid class analysis results list or NULL.
#' @param config          Full pipeline config.
#' @param out_dir         Output directory for this mode.
#' @return Character path to the generated .pptx file.
generate_lipidomics_pptx <- function(pre, qc_res, de_res, feature_sel_res,
                                      class_res, config, out_dir,
                                      biomarker_res  = NULL,
                                      pathway_res    = NULL,
                                      qc_enhanced    = NULL,
                                      clustering_res = NULL,
                                      pool_cv        = NULL) {

    if (!pptx_enabled(config, "lipidomics")) {
        message("PowerPoint generation disabled for lipidomics -- skipping")
        return(character(0))
    }

    if (!requireNamespace("officer", quietly = TRUE)) {
        warning("officer package not available -- skipping PowerPoint generation")
        return(character(0))
    }

    message("Generating lipidomics PowerPoint presentation...")

    lipid_cfg  <- config$modes$lipidomics
    de_cfg     <- lipid_cfg$de %||% list()
    norm_cfg   <- lipid_cfg$normalization %||% list()
    diag_dir   <- file.path(out_dir, "Diagnostic_plots")

    # Project info
    project_name <- config$project$name %||% "Lipidomics Analysis"
    analyst      <- gsub("_", " ", config$project$analyst %||% "")
    date_str     <- format(Sys.Date(), "%B %d, %Y")
    cond_col     <- de_cfg$condition_column %||% lipid_cfg$effects$color %||% "sample_type"

    # Group info
    groups <- if (!is.null(pre$meta) && cond_col %in% colnames(pre$meta)) {
        table(pre$meta[[cond_col]])
    } else NULL

    # DE stats
    n_features <- if (!is.null(pre$expr_filt)) nrow(pre$expr_filt) else NA
    n_samples  <- if (!is.null(pre$expr_filt)) ncol(pre$expr_filt) else NA
    n_de       <- if (!is.null(de_res$summary_df) && "pass_any_contrast" %in% colnames(de_res$summary_df)) {
        sum(de_res$summary_df$pass_any_contrast == 1, na.rm = TRUE)
    } else 0
    de_method  <- de_res$method %||% "unknown"

    # Thresholds
    p_cut <- de_cfg$p_cutoff %||% 0.05
    lfc_cut <- if (!is.null(de_cfg$logfc_cutoff)) de_cfg$logfc_cutoff else log2(de_cfg$linear_fc_cutoff %||% 1.5)

    # Contrast info
    contrasts <- names(de_res$de_tables)

    # Name resolver
    name_lut <- NULL
    if (!is.null(pre$row_data) && "Name" %in% colnames(pre$row_data)) {
        name_lut <- stats::setNames(as.character(pre$row_data$Name),
                                     as.character(pre$row_data$feature_id))
    }
    resolve <- function(ids) {
        if (!is.null(name_lut)) ifelse(is.na(name_lut[ids]), ids, name_lut[ids])
        else ids
    }

    # Footer
    footer_txt <- paste0("multiomics-core | ", analyst, " | ", date_str,
                          "   |   Generated by AI-assisted pipeline")

    # ---- Create presentation ----
    pptx <- officer::read_pptx()

    # ================================================================
    # SLIDE 1: Title
    # ================================================================
    groups_str <- if (!is.null(groups)) {
        paste(sprintf("%s (n=%d)", names(groups), as.integer(groups)), collapse = "  vs  ")
    } else "N/A"
    stats_text <- sprintf("%d lipids  |  %d samples  |  %s  |  %d DE lipids",
                           n_features, n_samples, groups_str, n_de)

    title_context <- sprintf(
        "Title slide for lipidomics analysis. Project: %s. Analyst: %s. ", project_name, analyst)
    if (!is.null(groups)) {
        title_context <- paste0(title_context,
            sprintf("Groups: %s. ", paste(sprintf("%s (n=%d)", names(groups), as.integer(groups)), collapse = ", ")))
    }
    title_context <- paste0(title_context,
        sprintf("%d lipids, %d samples, %d significant DE.", n_features, n_samples, n_de))
    title_bl <- generate_slide_bottom_line(title_context, config = config)

    pptx <- pptx_add_title_slide(pptx,
        main_title = "Lipidomics Analysis",
        project_name = project_name, analyst = analyst,
        date_str = date_str, stats_text = stats_text,
        bl = title_bl, footer = footer_txt)

    # ================================================================
    # SLIDE 2: Study Design
    # ================================================================
    design_context <- sprintf(
        "Study design. %d samples, %d lipids. Groups: %s. DE method: %s. Normalization: %s + %s.",
        n_samples, n_features, groups_str, de_method,
        norm_cfg$transform %||% "glog10", norm_cfg$scaling %||% "auto")
    design_bl <- generate_slide_bottom_line(design_context, config = config)

    design_items <- list(
        list(label = "Samples", value = as.character(n_samples)),
        list(label = "Lipids", value = as.character(n_features)),
        list(label = "Groups", value = groups_str),
        list(label = "DE Method", value = de_method),
        list(label = "Transform", value = norm_cfg$transform %||% "glog10"),
        list(label = "Scaling", value = norm_cfg$scaling %||% "auto"),
        list(label = "P-value cutoff", value = as.character(p_cut)),
        list(label = "log2(FC) cutoff", value = as.character(lfc_cut)),
        list(label = "DE lipids", value = as.character(n_de))
    )

    pptx <- pptx_add_design_slide(pptx, items = design_items,
                                    bl = design_bl, footer = footer_txt)

    # ================================================================
    # SLIDE: PERMANOVA (multivariate group-separation stats)
    # ================================================================
    permanova <- qc_enhanced$permanova
    if (!is.null(permanova) &&
        all(c("F_statistic", "R2", "p_value") %in% names(permanova))) {
        perm_items <- list(
            list(label = "Test",        value = "PERMANOVA (adonis2, Bray-Curtis)"),
            list(label = "F statistic", value = formatC(permanova$F_statistic, digits = 3, format = "f")),
            list(label = "R²",     value = formatC(permanova$R2,          digits = 3, format = "f")),
            list(label = "p-value",     value = formatC(permanova$p_value,     digits = 3, format = "g")),
            list(label = "Groups",      value = groups_str)
        )
        perm_context <- sprintf(
            "PERMANOVA result. F=%.3f, R2=%.3f, p=%.3g. Groups: %s.",
            permanova$F_statistic, permanova$R2, permanova$p_value, groups_str)
        perm_bl <- generate_slide_bottom_line(perm_context, config = config)
        pptx <- pptx_add_design_slide(pptx, items = perm_items,
                                       bl = perm_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE 3: PCA
    # ================================================================
    pca_png <- file.path(diag_dir, "PCA_PC1.vs.PC2.png")
    if (file.exists(pca_png)) {
        pca_context <- sprintf(
            "PCA plot (PC1 vs PC2). %d samples, groups: %s.", n_samples, groups_str)
        pca_bl <- generate_slide_bottom_line(pca_context, image_path = pca_png, config = config)
        pptx <- pptx_add_figure_slide(pptx, "PCA: PC1 vs PC2", pca_png,
                                  subtitle = sprintf("%d samples | %s", n_samples, groups_str),
                                  bl = pca_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE: PCA Loading plot
    # ================================================================
    pca_load_png <- file.path(diag_dir, "pca_loading_plot.png")
    if (file.exists(pca_load_png)) {
        load_context <- "PCA loading plot: top features driving PC1 and PC2 separation."
        load_bl <- generate_slide_bottom_line(load_context, image_path = pca_load_png, config = config)
        pptx <- pptx_add_figure_slide(pptx, "PCA: Top Loadings", pca_load_png,
                                  subtitle = "Features with largest |loading| on PC1/PC2",
                                  bl = load_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE: PCA Scree plot
    # ================================================================
    pca_scree_png <- file.path(diag_dir, "pca_scree_plot.png")
    if (file.exists(pca_scree_png)) {
        scree_context <- "PCA scree plot: variance explained per principal component."
        scree_bl <- generate_slide_bottom_line(scree_context, image_path = pca_scree_png, config = config)
        pptx <- pptx_add_figure_slide(pptx, "PCA: Scree Plot", pca_scree_png,
                                  subtitle = "Variance explained per PC",
                                  bl = scree_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE 4+: Volcano (per contrast)
    # ================================================================
    for (ctr in contrasts) {
        volcano_png <- file.path(diag_dir, paste0("volcano_", ctr, ".png"))
        if (!file.exists(volcano_png)) next

        ctr_tbl <- de_res$de_tables[[ctr]]
        n_up <- sum(!is.na(ctr_tbl$P.Value) & ctr_tbl$P.Value < p_cut &
                     !is.na(ctr_tbl$logFC) & ctr_tbl$logFC >= lfc_cut, na.rm = TRUE)
        n_down <- sum(!is.na(ctr_tbl$P.Value) & ctr_tbl$P.Value < p_cut &
                       !is.na(ctr_tbl$logFC) & ctr_tbl$logFC <= -lfc_cut, na.rm = TRUE)

        # Top hits
        sig_idx <- which(!is.na(ctr_tbl$P.Value) & ctr_tbl$P.Value < p_cut &
                          abs(ctr_tbl$logFC) >= lfc_cut)
        top_names <- ""
        if (length(sig_idx) > 0) {
            ordered_idx <- sig_idx[order(abs(ctr_tbl$logFC[sig_idx]), decreasing = TRUE)]
            top_ids <- ctr_tbl$feature_id[utils::head(ordered_idx, 8)]
            top_names <- paste(resolve(top_ids), collapse = ", ")
        }

        vol_stats <- sprintf(
            '{"contrast":"%s","up":%d,"down":%d,"total_tested":%d,"top":"%s"}',
            gsub("_vs_", " vs ", ctr), n_up, n_down, nrow(ctr_tbl), top_names)
        vol_context <- sprintf(
            "Volcano plot: %s. %d up, %d down (p<%.2g, |log2FC|>=%.1f). Top: %s.",
            gsub("_vs_", " vs ", ctr), n_up, n_down, p_cut, lfc_cut, top_names)
        vol_bl <- generate_slide_bottom_line(vol_context, stats_json = vol_stats,
                                              image_path = volcano_png, config = config)

        subtitle <- sprintf("Up: %d  |  Down: %d  |  Total DE: %d  (p < %s, |log2FC| >= %s)",
                             n_up, n_down, n_up + n_down, p_cut, lfc_cut)
        pptx <- pptx_add_figure_slide(pptx,
            paste("Volcano Plot:", gsub("_vs_", " vs ", ctr)),
            volcano_png, subtitle = subtitle, bl = vol_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE: MA plot (per contrast)
    # ================================================================
    for (ctr in contrasts) {
        ma_png <- file.path(diag_dir, paste0("MA_", ctr, ".png"))
        if (!file.exists(ma_png)) next

        ma_context <- sprintf("MA plot: %s. log2(FC) vs average expression.",
                               gsub("_vs_", " vs ", ctr))
        ma_bl <- generate_slide_bottom_line(ma_context, image_path = ma_png, config = config)
        pptx <- pptx_add_figure_slide(pptx,
            paste("MA Plot:", gsub("_vs_", " vs ", ctr)),
            ma_png, bl = ma_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE: Top DE lipids table (per contrast)
    # ================================================================
    for (ctr in contrasts) {
        ctr_tbl <- de_res$de_tables[[ctr]]
        if (is.null(ctr_tbl) || nrow(ctr_tbl) == 0) next

        sig <- ctr_tbl[!is.na(ctr_tbl$P.Value) & ctr_tbl$P.Value < p_cut &
                        abs(ctr_tbl$logFC) >= lfc_cut, , drop = FALSE]
        sig <- sig[order(sig$P.Value), ]
        top_n <- min(15, nrow(sig))
        if (top_n == 0) next

        top_tbl <- sig[seq_len(top_n), , drop = FALSE]
        display_df <- data.frame(
            Lipid       = resolve(as.character(top_tbl$feature_id)),
            `log2(FC)`  = round(top_tbl$logFC, 2),
            `P.Value`   = signif(top_tbl$P.Value, 3),
            `adj.P.Val` = signif(top_tbl$adj.P.Val, 3),
            check.names = FALSE, stringsAsFactors = FALSE
        )

        tbl_context <- sprintf(
            "Top %d DE lipids for %s. Top: %s (log2FC=%.2f, p=%.2e). Total DE: %d.",
            top_n, gsub("_vs_", " vs ", ctr),
            display_df$Lipid[1], display_df$`log2(FC)`[1],
            display_df$P.Value[1], nrow(sig))
        tbl_bl <- generate_slide_bottom_line(tbl_context, config = config)

        pptx <- pptx_add_table_slide(pptx,
            title = paste("Top DE Lipids:", gsub("_vs_", " vs ", ctr)),
            display_df = display_df,
            subtitle = sprintf("%d significant lipids (p < %s, |log2FC| >= %s)",
                               nrow(sig), p_cut, lfc_cut),
            bl = tbl_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE: DE Heatmap
    # ================================================================
    heatmap_pngs <- list.files(diag_dir, pattern = "^heatmap_top(10|25)_DE\\.png$", full.names = TRUE)
    if (length(heatmap_pngs) > 0) {
        hm_png <- heatmap_pngs[grepl("top25", heatmap_pngs)]
        if (length(hm_png) == 0) hm_png <- heatmap_pngs[1]
        hm_png <- hm_png[1]

        hm_context <- "Heatmap of top DE lipids with hierarchical clustering."
        hm_bl <- generate_slide_bottom_line(hm_context, image_path = hm_png, config = config)
        pptx <- pptx_add_figure_slide(pptx, "DE Lipids Heatmap", hm_png,
                                  subtitle = "Z-scored log2 intensities | hierarchical clustering",
                                  bl = hm_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE: P-value histogram (per contrast)
    # ================================================================
    for (ctr in contrasts) {
        phist_png <- file.path(diag_dir, paste0("pvalue_hist_", ctr, ".png"))
        if (!file.exists(phist_png)) next

        phist_context <- sprintf("P-value distribution for %s.", gsub("_vs_", " vs ", ctr))
        phist_bl <- generate_slide_bottom_line(phist_context, image_path = phist_png, config = config)
        pptx <- pptx_add_figure_slide(pptx,
            paste("P-value Distribution:", gsub("_vs_", " vs ", ctr)),
            phist_png, bl = phist_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE: Random Forest importance
    # ================================================================
    rf_png <- file.path(diag_dir, "rf_importance.png")
    if (file.exists(rf_png) && !is.null(feature_sel_res$rf)) {
        rf_imp <- feature_sel_res$rf$importance
        rf_top_names <- character(0)
        if (!is.null(rf_imp) && is.data.frame(rf_imp) && nrow(rf_imp) > 0) {
            imp_col <- if ("MeanDecreaseAccuracy" %in% colnames(rf_imp)) {
                "MeanDecreaseAccuracy"
            } else if ("importance" %in% colnames(rf_imp)) {
                "importance"
            } else setdiff(colnames(rf_imp), "feature_id")[1]
            sorted_idx <- order(rf_imp[[imp_col]], decreasing = TRUE)
            top_rf <- rf_imp[utils::head(sorted_idx, 5), , drop = FALSE]
            top_ids <- if ("feature_id" %in% colnames(top_rf)) as.character(top_rf$feature_id) else rownames(top_rf)
            rf_top_names <- resolve(top_ids)
        }

        rf_context <- sprintf("Random Forest importance. Top features: %s.",
                               paste(rf_top_names, collapse = ", "))
        rf_bl <- generate_slide_bottom_line(rf_context, image_path = rf_png, config = config)
        pptx <- pptx_add_figure_slide(pptx, "Random Forest: Variable Importance", rf_png,
                                  subtitle = paste("Top:", paste(rf_top_names, collapse = ", ")),
                                  bl = rf_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE: PLS-DA scores
    # ================================================================
    plsda_png <- file.path(diag_dir, "plsda_scores.png")
    if (file.exists(plsda_png) && !is.null(feature_sel_res$plsda)) {
        plsda_context <- sprintf("PLS-DA scores. Supervised separation of %s.", groups_str)
        plsda_bl <- generate_slide_bottom_line(plsda_context, image_path = plsda_png, config = config)
        pptx <- pptx_add_figure_slide(pptx, "PLS-DA: Scores Plot", plsda_png,
                                  subtitle = sprintf("Supervised classification | %s", groups_str),
                                  bl = plsda_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE: PLS-DA VIP
    # ================================================================
    vip_png <- file.path(diag_dir, "plsda_vip_scores.png")
    if (file.exists(vip_png) && !is.null(feature_sel_res$plsda)) {
        vip_context <- "PLS-DA VIP scores. Features with VIP > 1 are important discriminators."
        vip_bl <- generate_slide_bottom_line(vip_context, image_path = vip_png, config = config)
        pptx <- pptx_add_figure_slide(pptx, "PLS-DA: VIP Scores", vip_png,
                                  subtitle = "Variable Importance in Projection | VIP > 1 threshold",
                                  bl = vip_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE: PLS-DA Cross-Validation
    # ================================================================
    plsda_cv_png <- file.path(diag_dir, "plsda_cross_validation.png")
    if (file.exists(plsda_cv_png)) {
        cv_context <- "PLS-DA cross-validation. Classification error / Q2 across components."
        cv_bl <- generate_slide_bottom_line(cv_context, image_path = plsda_cv_png, config = config)
        pptx <- pptx_add_figure_slide(pptx, "PLS-DA: Cross-Validation", plsda_cv_png,
                                  subtitle = "Held-out classification error across components",
                                  bl = cv_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE: PLS-DA Confusion Matrix
    # ================================================================
    plsda_cm_png <- file.path(diag_dir, "plsda_confusion_matrix.png")
    if (file.exists(plsda_cm_png)) {
        cm_context <- sprintf("PLS-DA confusion matrix. Predicted vs actual %s.", groups_str)
        cm_bl <- generate_slide_bottom_line(cm_context, image_path = plsda_cm_png, config = config)
        pptx <- pptx_add_figure_slide(pptx, "PLS-DA: Confusion Matrix", plsda_cm_png,
                                  subtitle = sprintf("Predicted vs actual | %s", groups_str),
                                  bl = cm_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE: Sample correlation
    # ================================================================
    cor_png <- file.path(diag_dir, "sample_correlation_heatmap.png")
    if (file.exists(cor_png)) {
        cor_context <- "Sample-to-sample Pearson correlation after normalization."
        cor_bl <- generate_slide_bottom_line(cor_context, image_path = cor_png, config = config)
        pptx <- pptx_add_figure_slide(pptx, "Sample Correlation Heatmap", cor_png,
                                  bl = cor_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE: Pool CV QC
    # ================================================================
    pool_cv_png <- file.path(diag_dir, "pool_cv_density.png")
    if (!is.null(pool_cv) && !is.null(pool_cv$cv_result) && file.exists(pool_cv_png)) {
        pcv <- pool_cv$cv_result
        pool_subtitle <- sprintf(
            "Median CV = %.1f%%  |  %d features  |  %d pools",
            pcv$median_cv, pcv$n_features, pcv$n_pools)
        pool_context <- sprintf(
            "Pool QC: per-feature coefficient of variation across %d QC pool samples. Median CV = %.1f%% (n=%d features).",
            pcv$n_pools, pcv$median_cv, pcv$n_features)
        pool_bl <- generate_slide_bottom_line(pool_context, image_path = pool_cv_png, config = config)
        pptx <- pptx_add_figure_slide(pptx, "Pool QC: CV Distribution", pool_cv_png,
                                  subtitle = pool_subtitle, bl = pool_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE: Lipid Class Composition
    # ================================================================
    class_dir <- file.path(out_dir, "Lipid_class")
    if (!dir.exists(class_dir)) class_dir <- file.path(out_dir, "LipidClass")

    class_comp_png <- file.path(class_dir, "lipid_class_composition.png")
    if (!file.exists(class_comp_png)) {
        class_comp_png <- list.files(class_dir, pattern = "class_composition.*\\.png$",
                                      full.names = TRUE, recursive = TRUE)[1]
    }
    if (!is.na(class_comp_png) && file.exists(class_comp_png)) {
        n_classes <- if (!is.null(class_res$class_summary)) nrow(class_res$class_summary) else "N/A"
        comp_context <- sprintf("Lipid class composition. %s lipid classes detected across samples.", n_classes)
        comp_bl <- generate_slide_bottom_line(comp_context, image_path = class_comp_png, config = config)
        pptx <- pptx_add_figure_slide(pptx, "Lipid Class Composition", class_comp_png,
                                  subtitle = sprintf("%s lipid classes | per-group composition", n_classes),
                                  bl = comp_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE: Lipid Class ORA
    # ================================================================
    ora_png <- file.path(class_dir, "lipid_class_ora.png")
    if (!file.exists(ora_png)) {
        ora_png <- list.files(class_dir, pattern = "ora.*\\.png$",
                               full.names = TRUE, recursive = TRUE)[1]
    }
    if (!is.na(ora_png) && file.exists(ora_png)) {
        ora_context <- "Lipid class over-representation analysis (ORA) on DE significant lipids."
        ora_bl <- generate_slide_bottom_line(ora_context, image_path = ora_png, config = config)
        pptx <- pptx_add_figure_slide(pptx, "Lipid Class Enrichment (ORA)", ora_png,
                                  subtitle = "Over-representation of DE lipids in lipid classes",
                                  bl = ora_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE: Chain Length / Saturation Analysis
    # ================================================================
    chain_png <- file.path(class_dir, "chain_analysis.png")
    if (!file.exists(chain_png)) {
        chain_png <- list.files(class_dir, pattern = "chain.*\\.png$",
                                 full.names = TRUE, recursive = TRUE)[1]
    }
    if (!is.na(chain_png) && file.exists(chain_png)) {
        chain_context <- "Chain length and saturation profiling of detected lipid species."
        chain_bl <- generate_slide_bottom_line(chain_context, image_path = chain_png, config = config)
        pptx <- pptx_add_figure_slide(pptx, "Chain Length & Saturation Analysis", chain_png,
                                  subtitle = "Acyl chain composition across lipid classes",
                                  bl = chain_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE: Lipid Class Correlation Heatmap
    # ================================================================
    class_cor_png <- file.path(diag_dir, "lipid_class_correlation.png")
    if (file.exists(class_cor_png)) {
        ccor_context <- "Inter-class correlation: which lipid classes co-vary across samples."
        ccor_bl <- generate_slide_bottom_line(ccor_context, image_path = class_cor_png, config = config)
        pptx <- pptx_add_figure_slide(pptx, "Lipid Class Correlation", class_cor_png,
                                  subtitle = "Pearson correlation between lipid class profiles",
                                  bl = ccor_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE: Lipid Category Donut (one slide per group)
    # ================================================================
    donut_pngs <- list.files(diag_dir, pattern = "^lipid_category_donut_.*\\.png$",
                              full.names = TRUE)
    for (dp in donut_pngs) {
        grp_label <- sub("^lipid_category_donut_(.*)\\.png$", "\\1", basename(dp))
        donut_context <- sprintf(
            "Lipid category composition for group %s. Relative abundance per category.",
            grp_label)
        donut_bl <- generate_slide_bottom_line(donut_context, image_path = dp, config = config)
        pptx <- pptx_add_figure_slide(pptx,
            paste("Lipid Category Composition:", grp_label),
            dp, subtitle = sprintf("Group: %s", grp_label),
            bl = donut_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE: Hierarchical Clustering Heatmap
    # ================================================================
    hier_png <- file.path(out_dir, "Clustering", "Hierarchical",
                          "Hierarchical_DE_heatmap.png")
    if (file.exists(hier_png)) {
        n_de_clust <- if (!is.null(clustering_res$objects$hm_hier_de$feature_ids)) {
            length(clustering_res$objects$hm_hier_de$feature_ids)
        } else NA_integer_
        hier_context <- sprintf(
            "Hierarchical clustering of %s DE lipids. Rows ordered by dendrogram.",
            ifelse(is.na(n_de_clust), "the", as.character(n_de_clust)))
        hier_bl <- generate_slide_bottom_line(hier_context, image_path = hier_png, config = config)
        pptx <- pptx_add_figure_slide(pptx, "Clustering: Hierarchical (DE features)",
            hier_png,
            subtitle = if (is.na(n_de_clust)) "Z-scored intensities | row dendrogram"
                       else sprintf("%d DE features | Z-scored | row dendrogram", n_de_clust),
            bl = hier_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE: Partition Clustering Heatmap
    # ================================================================
    part_pngs <- list.files(
        file.path(out_dir, "Clustering", "Partition_clustering"),
        pattern = "^Partition_clustering_heatmap\\.png$",
        recursive = TRUE, full.names = TRUE)
    if (length(part_pngs) > 0) {
        part_png <- part_pngs[1]
        part_k <- clustering_res$excel_order$partition_k
        part_context <- sprintf(
            "Partition clustering%s. DE lipids grouped by expression profile.",
            if (!is.null(part_k)) sprintf(" (k=%d)", part_k) else "")
        part_bl <- generate_slide_bottom_line(part_context, image_path = part_png, config = config)
        pptx <- pptx_add_figure_slide(pptx, "Clustering: Partition (DE features)",
            part_png,
            subtitle = if (is.null(part_k)) "Z-scored | clusters separated by row gaps"
                       else sprintf("k = %d clusters | Z-scored | row gaps mark clusters", part_k),
            bl = part_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE: Biomarker Discovery Table (figure)
    # ================================================================
    bm_fig_png <- file.path(diag_dir, "biomarker_table.png")
    if (file.exists(bm_fig_png)) {
        bm_df <- biomarker_res$biomarker_df
        n_cand <- if (!is.null(bm_df)) sum(bm_df$is_candidate, na.rm = TRUE) else 0L
        bm_context <- sprintf(
            "Top biomarker candidates ranked by t-test p-value. %d candidates flagged. Metrics: p-value, AUC, Cohen's d, power, log2FC.",
            n_cand)
        bm_bl <- generate_slide_bottom_line(bm_context, image_path = bm_fig_png, config = config)
        pptx <- pptx_add_figure_slide(pptx, "Biomarker Discovery: Top Candidates",
            bm_fig_png,
            subtitle = sprintf("%d candidates | metrics colour-scaled per column", n_cand),
            bl = bm_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE: Top Biomarkers Table (data)
    # ================================================================
    bm_df <- biomarker_res$biomarker_df
    if (!is.null(bm_df) && nrow(bm_df) > 0) {
        top_n_bm <- min(15L, nrow(bm_df))
        top_bm <- bm_df[seq_len(top_n_bm), , drop = FALSE]
        label_col <- if ("display_name" %in% colnames(top_bm)) "display_name" else "feature_id"
        bm_display <- data.frame(
            Lipid       = top_bm[[label_col]],
            AUC         = round(top_bm$AUC, 3),
            `Cohen's d` = round(top_bm$cohens_d, 3),
            `log2(FC)`  = round(top_bm$log2FC, 2),
            `P.Value`   = signif(top_bm$p_value, 3),
            check.names = FALSE, stringsAsFactors = FALSE
        )
        top_bm_context <- sprintf(
            "Top %d biomarker candidates. Best AUC = %.3f for %s.",
            top_n_bm, max(bm_display$AUC, na.rm = TRUE),
            bm_display$Lipid[which.max(bm_display$AUC)])
        top_bm_bl <- generate_slide_bottom_line(top_bm_context, config = config)
        pptx <- pptx_add_table_slide(pptx,
            title = "Top Biomarker Candidates",
            display_df = bm_display,
            subtitle = sprintf("Ranked by t-test p-value | %d shown", top_n_bm),
            bl = top_bm_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE: ROC Curves (top lipids)
    # ================================================================
    roc_png <- file.path(diag_dir, "roc_curves_top_lipids.png")
    if (file.exists(roc_png)) {
        roc_context <- "ROC curves for top lipid biomarkers. AUC values shown in legend."
        roc_bl <- generate_slide_bottom_line(roc_context, image_path = roc_png, config = config)
        pptx <- pptx_add_figure_slide(pptx, "ROC Curves: Top Lipid Biomarkers",
            roc_png,
            subtitle = "Per-feature ROC | AUC labelled in legend",
            bl = roc_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE: Multivariate ROC (Random Forest)
    # ================================================================
    mvroc_png <- file.path(diag_dir, "roc_multivariate_rf.png")
    if (file.exists(mvroc_png)) {
        mv_auc <- biomarker_res$mv_roc$auc
        mv_subtitle <- if (!is.null(mv_auc))
            sprintf("Random Forest OOB | AUC = %.3f", mv_auc)
        else "Random Forest OOB predictions"
        mv_context <- sprintf(
            "Multivariate ROC: Random Forest on all lipid features%s.",
            if (!is.null(mv_auc)) sprintf(" — AUC = %.3f", mv_auc) else "")
        mv_bl <- generate_slide_bottom_line(mv_context, image_path = mvroc_png, config = config)
        pptx <- pptx_add_figure_slide(pptx, "Multivariate ROC (Random Forest)",
            mvroc_png, subtitle = mv_subtitle, bl = mv_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE: Lipid Pathway Barplot
    # ================================================================
    pw_bar_png <- file.path(diag_dir, "lipid_pathway_barplot.png")
    if (file.exists(pw_bar_png)) {
        n_pw <- if (!is.null(pathway_res$pathway_scores)) nrow(pathway_res$pathway_scores) else NA
        pw_context <- sprintf(
            "Lipid pathway scores. %s pathways evaluated; bars show enrichment significance.",
            ifelse(is.na(n_pw), "Multiple", as.character(n_pw)))
        pw_bl <- generate_slide_bottom_line(pw_context, image_path = pw_bar_png, config = config)
        pptx <- pptx_add_figure_slide(pptx, "Lipid Pathway Enrichment",
            pw_bar_png,
            subtitle = if (is.na(n_pw)) "Pathway scores from DE lipid composition"
                       else sprintf("%d pathways evaluated", n_pw),
            bl = pw_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE: Lipid Pathway Network
    # ================================================================
    pw_net_png <- file.path(diag_dir, "lipid_pathway_network.png")
    if (file.exists(pw_net_png)) {
        pwn_context <- "Lipid pathway network. Nodes = pathways, edges = shared species."
        pwn_bl <- generate_slide_bottom_line(pwn_context, image_path = pw_net_png, config = config)
        pptx <- pptx_add_figure_slide(pptx, "Lipid Pathway Network",
            pw_net_png,
            subtitle = "Nodes: pathways | edges: shared lipid species",
            bl = pwn_bl, footer = footer_txt)
    }

    # ================================================================
    # SLIDE: Enzyme Interaction Network (STRING)
    # ================================================================
    enz_png <- file.path(diag_dir, "enzyme_interaction_network.png")
    if (file.exists(enz_png)) {
        n_enz <- if (!is.null(pathway_res$enzyme_predictions))
            length(unique(pathway_res$enzyme_predictions$gene_symbol)) else NA
        enz_context <- sprintf(
            "STRING protein-protein interaction network of predicted enzymes (%s genes).",
            ifelse(is.na(n_enz), "multiple", as.character(n_enz)))
        enz_bl <- generate_slide_bottom_line(enz_context, image_path = enz_png, config = config)
        pptx <- pptx_add_figure_slide(pptx, "Enzyme Interaction Network (STRING)",
            enz_png,
            subtitle = if (is.na(n_enz)) "Predicted enzymes from differential lipid classes"
                       else sprintf("%d predicted enzymes | STRING interactions", n_enz),
            bl = enz_bl, footer = footer_txt)
    }

    # ---- Save to Results root (parent of mode dir) ----
    results_root <- dirname(out_dir)
    out_file <- file.path(results_root, "lipidomics_summary.pptx")
    print(pptx, target = out_file)
    message("PowerPoint saved: ", out_file)
    out_file
}
