# R/domain/lipidomics/12_commentary.R
# Figure discovery for lipidomics AI commentary
#
# Scans the lipidomics output directory for all PNG plots generated
# by the pipeline modules and builds a metadata table for the
# commentary engine (R/services/12_commentary.R).


#' Discover all figure files from the lipidomics output directory
#'
#' Scans Diagnostic_plots/ for PNG files generated by lipidomics modules
#' (QC, DE, feature selection, class analysis, biomarker, pathway, enhanced QC)
#' and builds a metadata table compatible with \code{generate_all_commentary()}.
#'
#' @param out_dir  Lipidomics output directory (e.g. .../lipidomics)
#' @param config   Full pipeline config
#' @return Data frame with figure_id, filepath, plot_type, section, title, etc.
discover_lipidomics_figures <- function(out_dir, config = NULL) {

    diag_dir <- file.path(out_dir, "Diagnostic_plots")

    figures <- list()

    add_if_exists <- function(id, filename, dir, plot_type, section, title, desc,
                               x_axis = NA, y_axis = NA) {
        fp <- file.path(dir, filename)
        if (file.exists(fp)) {
            figures[[id]] <<- data.frame(
                figure_id   = id,
                filepath    = fp,
                plot_type   = plot_type,
                section     = section,
                title       = title,
                description = desc,
                x_axis      = x_axis,
                y_axis      = y_axis,
                contrast    = NA_character_,
                stringsAsFactors = FALSE
            )
        }
    }

    # ---- QC Pre: PCA ----
    add_if_exists("pca_plot", "PCA_PC1.vs.PC2.png", diag_dir,
                  "scatter", "QC", "PCA Plot — PC1 vs PC2",
                  "Principal component analysis of lipidomics samples — first two components",
                  "PC1", "PC2")

    # Also try with color suffixes (the QC module appends _by_{color_col})
    if (dir.exists(diag_dir)) {
        pca12_files <- list.files(diag_dir, pattern = "^PCA_PC1\\.vs\\.PC2.*\\.png$", full.names = TRUE)
        for (pf in pca12_files) {
            bn <- basename(pf)
            if (bn == "PCA_PC1.vs.PC2.png") next
            suffix <- gsub("^PCA_PC1\\.vs\\.PC2_?|\\.png$", "", bn)
            fid <- paste0("pca_plot_", suffix)
            figures[[fid]] <- data.frame(
                figure_id = fid, filepath = pf, plot_type = "scatter",
                section = "QC", title = paste("PCA Plot — PC1 vs PC2", suffix),
                description = paste("PCA of lipidomics samples colored by", gsub("_", " ", suffix)),
                x_axis = "PC1", y_axis = "PC2", contrast = NA_character_,
                stringsAsFactors = FALSE
            )
        }
    }

    add_if_exists("pca_plot_13", "PCA_PC1.vs.PC3.png", diag_dir,
                  "scatter", "QC", "PCA Plot — PC1 vs PC3",
                  "PCA of lipidomics samples — first and third components",
                  "PC1", "PC3")

    # ---- QC Pre: Density ----
    add_if_exists("density_raw", "intensity_density_raw.png", diag_dir,
                  "density", "QC", "Raw Intensity Density",
                  "Per-sample density distribution of raw lipid intensities",
                  "Intensity", "Density")

    # Try with tag suffixes
    if (dir.exists(diag_dir)) {
        for (pat in c("intensity_density_raw", "intensity_density_normalized")) {
            dens_files <- list.files(diag_dir, pattern = paste0("^", pat, ".*\\.png$"), full.names = TRUE)
            for (df in dens_files) {
                bn <- basename(df)
                base_name <- gsub("\\.png$", "", bn)
                tag <- gsub(paste0("^", pat, "_?"), "", base_name)
                fid <- if (nzchar(tag)) paste0(gsub("intensity_", "", pat), "_", tag) else gsub("intensity_", "", pat)
                if (fid %in% names(figures)) next
                is_raw <- grepl("raw", pat)
                figures[[fid]] <- data.frame(
                    figure_id = fid, filepath = df, plot_type = "density",
                    section = "QC",
                    title = paste(if (is_raw) "Raw" else "Normalized", "Intensity Density", tag),
                    description = paste("Per-sample density distribution of",
                                       if (is_raw) "raw" else "normalized", "lipid intensities"),
                    x_axis = "Intensity", y_axis = "Density", contrast = NA_character_,
                    stringsAsFactors = FALSE
                )
            }
        }
    }

    # ---- QC Pre: Boxplots ----
    add_if_exists("boxplot_raw", "intensity_boxplot_raw.png", diag_dir,
                  "boxplot", "QC", "Raw Intensity Boxplot",
                  "Per-sample boxplot of raw lipid intensities before normalization",
                  "Sample", "Intensity")

    if (dir.exists(diag_dir)) {
        for (pat in c("intensity_boxplot_raw", "intensity_boxplot_normalized")) {
            box_files <- list.files(diag_dir, pattern = paste0("^", pat, ".*\\.png$"), full.names = TRUE)
            for (bf in box_files) {
                bn <- basename(bf)
                base_name <- gsub("\\.png$", "", bn)
                tag <- gsub(paste0("^", pat, "_?"), "", base_name)
                fid <- if (nzchar(tag)) paste0(gsub("intensity_", "", pat), "_", tag) else gsub("intensity_", "", pat)
                if (fid %in% names(figures)) next
                is_raw <- grepl("raw", pat)
                figures[[fid]] <- data.frame(
                    figure_id = fid, filepath = bf, plot_type = "boxplot",
                    section = "QC",
                    title = paste(if (is_raw) "Raw" else "Normalized", "Intensity Boxplot", tag),
                    description = paste("Per-sample boxplot of",
                                       if (is_raw) "raw" else "normalized", "lipid intensities"),
                    x_axis = "Sample", y_axis = "Intensity", contrast = NA_character_,
                    stringsAsFactors = FALSE
                )
            }
        }
    }

    # ---- QC Pre: Heatmaps ----
    add_if_exists("sample_distance", "sample_distance_heatmap.png", diag_dir,
                  "heatmap", "QC", "Sample Distance Heatmap",
                  "Euclidean distance matrix between samples based on normalized lipid profiles",
                  "Samples", "Samples")

    add_if_exists("sample_correlation", "sample_correlation_heatmap.png", diag_dir,
                  "heatmap", "QC", "Sample Correlation Heatmap",
                  "Pearson correlation matrix between samples based on normalized lipid profiles",
                  "Samples", "Samples")

    # ---- Differential Expression: Volcano, MA, P-value hist (per contrast) ----
    if (dir.exists(diag_dir)) {
        volcano_files <- list.files(diag_dir, pattern = "^volcano_.*\\.png$", full.names = TRUE)
        for (vf in volcano_files) {
            cn <- gsub("^volcano_|\\.png$", "", basename(vf))
            fid <- paste0("volcano_", cn)
            figures[[fid]] <- data.frame(
                figure_id = fid, filepath = vf, plot_type = "volcano",
                section = "Differential Expression",
                title = paste("Volcano Plot:", gsub("_", " ", cn)),
                description = "Statistical significance vs fold change for all lipids in this contrast",
                x_axis = "log2 Fold Change", y_axis = "-log10(p-value)",
                contrast = cn, stringsAsFactors = FALSE
            )
        }

        ma_files <- list.files(diag_dir, pattern = "^MA_.*\\.png$", full.names = TRUE)
        for (mf in ma_files) {
            cn <- gsub("^MA_|\\.png$", "", basename(mf))
            fid <- paste0("ma_", cn)
            figures[[fid]] <- data.frame(
                figure_id = fid, filepath = mf, plot_type = "ma_plot",
                section = "Differential Expression",
                title = paste("MA Plot:", gsub("_", " ", cn)),
                description = "Mean-difference plot: fold change vs average expression for all lipids",
                x_axis = "Average Expression", y_axis = "log2 Fold Change",
                contrast = cn, stringsAsFactors = FALSE
            )
        }

        pval_files <- list.files(diag_dir, pattern = "^pvalue_hist_.*\\.png$", full.names = TRUE)
        for (pf in pval_files) {
            cn <- gsub("^pvalue_hist_|\\.png$", "", basename(pf))
            fid <- paste0("pvalue_hist_", cn)
            figures[[fid]] <- data.frame(
                figure_id = fid, filepath = pf, plot_type = "histogram",
                section = "Differential Expression",
                title = paste("P-value Distribution:", gsub("_", " ", cn)),
                description = "Distribution of raw p-values for this contrast",
                x_axis = "p-value", y_axis = "Frequency",
                contrast = cn, stringsAsFactors = FALSE
            )
        }
    }

    # ---- Feature Selection: RF + PLS-DA ----
    add_if_exists("rf_importance", "rf_importance.png", diag_dir,
                  "bar", "Feature Selection", "Random Forest Variable Importance",
                  "Top lipids ranked by Random Forest mean decrease in accuracy",
                  "Mean Decrease Accuracy", "Lipid")

    add_if_exists("plsda_scores", "plsda_scores.png", diag_dir,
                  "scatter", "Feature Selection", "PLS-DA Scores Plot",
                  "PLS-DA scores showing sample separation along latent components",
                  "Component 1", "Component 2")

    add_if_exists("plsda_vip", "plsda_vip_scores.png", diag_dir,
                  "bar", "Feature Selection", "PLS-DA VIP Scores",
                  "Variable Importance in Projection scores from PLS-DA model",
                  "VIP Score", "Lipid")

    # ---- Lipid Class Analysis ----
    add_if_exists("class_absolute", "lipid_class_absolute.png", diag_dir,
                  "bar", "Lipid Class Analysis", "Lipid Class Composition (Absolute)",
                  "Absolute count of detected lipid species per class",
                  "Lipid Class", "Count")

    add_if_exists("class_normalized", "lipid_class_normalized.png", diag_dir,
                  "bar", "Lipid Class Analysis", "Lipid Class Composition (Normalized)",
                  "Normalized intensity distribution across lipid classes per sample",
                  "Sample", "Normalized Intensity")

    add_if_exists("chain_saturation", "chain_saturation.png", diag_dir,
                  "bar", "Lipid Class Analysis", "Chain Saturation Analysis",
                  "Distribution of lipid species by chain saturation degree",
                  "Saturation", "Count")

    add_if_exists("chain_length", "chain_length_distribution.png", diag_dir,
                  "bar", "Lipid Class Analysis", "Chain Length Distribution",
                  "Distribution of lipid species by total chain length",
                  "Chain Length", "Count")

    add_if_exists("class_ora", "lipid_class_ora.png", diag_dir,
                  "dot", "Lipid Class Analysis", "Lipid Class Over-Representation",
                  "Over-representation analysis of DE lipids within lipid classes",
                  "Enrichment Score", "Lipid Class")

    # ---- Biomarker Discovery ----
    add_if_exists("biomarker_table", "biomarker_table.png", diag_dir,
                  "bar", "Biomarker Discovery", "Biomarker Metrics",
                  "Top candidate biomarker lipids ranked by AUC, effect size, and significance",
                  "Metric", "Lipid")

    add_if_exists("roc_curves", "roc_curves_top_lipids.png", diag_dir,
                  "line", "Biomarker Discovery", "ROC Curves — Top Lipids",
                  "Receiver operating characteristic curves for top discriminating lipids",
                  "False Positive Rate", "True Positive Rate")

    add_if_exists("roc_multivariate", "roc_multivariate_rf.png", diag_dir,
                  "line", "Biomarker Discovery", "Multivariate ROC — Random Forest",
                  "ROC curve from Random Forest multivariate classifier",
                  "False Positive Rate", "True Positive Rate")

    # ---- Pathway Analysis ----
    add_if_exists("pathway_network", "lipid_pathway_network.png", diag_dir,
                  "network", "Lipid Pathway Analysis", "Lipid Pathway Network",
                  "Network showing predicted enzymatic conversion pathways between lipid classes",
                  NA, NA)

    add_if_exists("pathway_barplot", "lipid_pathway_barplot.png", diag_dir,
                  "bar", "Lipid Pathway Analysis", "Pathway Enrichment Barplot",
                  "Lipid metabolic pathways ranked by enrichment score",
                  "Enrichment Score", "Pathway")

    add_if_exists("enzyme_network", "enzyme_interaction_network.png", diag_dir,
                  "network", "Lipid Pathway Analysis", "Enzyme Interaction Network",
                  "STRING protein-protein interaction network of predicted lipid-metabolizing enzymes",
                  NA, NA)

    # ---- Enhanced QC ----
    add_if_exists("pca_scree", "pca_scree_plot.png", diag_dir,
                  "bar", "Enhanced QC", "PCA Scree Plot",
                  "Proportion of variance explained by each principal component",
                  "Principal Component", "Variance Explained (%)")

    add_if_exists("pca_loading", "pca_loading_plot.png", diag_dir,
                  "bar", "Enhanced QC", "PCA Loading Plot",
                  "Contribution of individual lipid features to the first two principal components",
                  "Loading (PC1)", "Loading (PC2)")

    add_if_exists("plsda_cv", "plsda_cross_validation.png", diag_dir,
                  "line", "Enhanced QC", "PLS-DA Cross-Validation",
                  "Cross-validation performance of PLS-DA model across components",
                  "Number of Components", "Error Rate")

    add_if_exists("plsda_confusion", "plsda_confusion_matrix.png", diag_dir,
                  "heatmap", "Enhanced QC", "PLS-DA Confusion Matrix",
                  "Confusion matrix from PLS-DA cross-validation predictions",
                  "Predicted", "Actual")

    add_if_exists("class_correlation", "lipid_class_correlation.png", diag_dir,
                  "heatmap", "Enhanced QC", "Lipid Class Correlation",
                  "Correlation matrix of mean intensities between lipid classes",
                  "Lipid Class", "Lipid Class")

    add_if_exists("category_donut", "lipid_category_donut.png", diag_dir,
                  "pie", "Enhanced QC", "Lipid Category Composition",
                  "Distribution of detected lipids across major lipid categories",
                  NA, NA)

    # ---- Return ----
    if (length(figures) == 0) {
        message("No lipidomics figures discovered for commentary")
        return(data.frame(
            figure_id = character(), filepath = character(),
            plot_type = character(), section = character(),
            title = character(), description = character(),
            x_axis = character(), y_axis = character(),
            contrast = character(), stringsAsFactors = FALSE
        ))
    }

    figures_tbl <- do.call(rbind, figures)
    rownames(figures_tbl) <- NULL
    message("Discovered ", nrow(figures_tbl), " lipidomics figures for commentary")
    figures_tbl
}
