# =============================================================================
# Figure Commentary Generation for Multi-Omics Integration Pipeline
# =============================================================================
# This module generates AI-powered or data-driven commentary for pipeline figures
# Supports Claude Vision API, OpenAI GPT-4 Vision API, or deterministic fallback
#
# Fallback functions are defined in R/domain/multiomics/13b_commentary_fallbacks.R
# Note: tar_source() auto-sources all R files, no explicit source() needed

#' Build a table of all figures generated by the pipeline with metadata
#'
#' @param mae MultiAssayExperiment object
#' @param foundational_results Results from foundational correlation analysis
#' @param mechanistic_results Results from mechanistic pathway analysis
#' @param integration_results Results from integration methods (MOFA, DIABLO, SNF)
#' @param concordance_results Cross-omics concordance results
#' @param enrichment_results Pathway enrichment results
#' @param consensus_results Results from consensus analysis
#' @param stability_results Results from stability analysis
#' @param config Pipeline configuration
#' @param out_dir Output directory base
#' @return A tibble with figure paths and metadata
build_figures_table <- function(mae,
                                foundational_results = NULL,
                                mechanistic_results = NULL,
                                integration_results = NULL,
                                concordance_results = NULL,
                                enrichment_results = NULL,
                                consensus_results = NULL,
                                stability_results = NULL,
                                config,
                                out_dir) {
    message("Building figures metadata table...")

    plots_dir <- file.path(out_dir, "plots")
    omics_present <- names(mae@ExperimentList)

    figures <- list()

    # ---------------------------------------------------------------------------
    # MOFA2 Figures
    # ---------------------------------------------------------------------------
    if (!is.null(integration_results$mofa)) {
        # Variance heatmap
        fig_path <- file.path(plots_dir, "mofa_variance_heatmap.png")
        if (file.exists(fig_path)) {
            figures[["mofa_variance_heatmap"]] <- list(
                figure_id = "mofa_variance_heatmap",
                file_path = fig_path,
                plot_type = "heatmap",
                title = "MOFA2 Variance Explained Heatmap",
                description = "Heatmap showing variance explained by each MOFA factor in each omics view",
                section = "MOFA2 Integration",
                x_axis = "Factor",
                y_axis = "Omics View"
            )
        }

        # Factor scatter plot
        fig_path <- file.path(plots_dir, "mofa_factors_1_2.png")
        if (file.exists(fig_path)) {
            figures[["mofa_factors_1_2"]] <- list(
                figure_id = "mofa_factors_1_2",
                file_path = fig_path,
                plot_type = "scatter",
                title = "MOFA2 Factor Plot (Factor 1 vs 2)",
                description = "Scatter plot of samples in MOFA factor space colored by condition",
                section = "MOFA2 Integration",
                x_axis = "Factor 1",
                y_axis = "Factor 2"
            )
        }

        # Factor weights
        for (omic in omics_present) {
            fig_path <- file.path(plots_dir, paste0("mofa_weights_", omic, ".png"))
            if (file.exists(fig_path)) {
                figures[[paste0("mofa_weights_", omic)]] <- list(
                    figure_id = paste0("mofa_weights_", omic),
                    file_path = fig_path,
                    plot_type = "bar",
                    title = paste0("MOFA2 Feature Weights - ", tools::toTitleCase(omic)),
                    description = paste0("Top contributing features to MOFA factors from ", omic),
                    section = "MOFA2 Integration",
                    x_axis = "Feature",
                    y_axis = "Weight"
                )
            }
        }
    }

    # ---------------------------------------------------------------------------
    # DIABLO Figures
    # ---------------------------------------------------------------------------
    if (!is.null(integration_results$diablo)) {
        # Sample plot
        fig_path <- file.path(plots_dir, "diablo_sample_plot_comp1_2.png")
        if (file.exists(fig_path)) {
            figures[["diablo_sample_plot"]] <- list(
                figure_id = "diablo_sample_plot",
                file_path = fig_path,
                plot_type = "scatter",
                title = "DIABLO Sample Plot",
                description = "Samples in DIABLO component space, showing separation by condition",
                section = "DIABLO Integration",
                x_axis = "Component 1",
                y_axis = "Component 2"
            )
        }

        # Loading plots
        for (omic in omics_present) {
            fig_path <- file.path(plots_dir, paste0("diablo_loadings_", omic, ".png"))
            if (file.exists(fig_path)) {
                figures[[paste0("diablo_loadings_", omic)]] <- list(
                    figure_id = paste0("diablo_loadings_", omic),
                    file_path = fig_path,
                    plot_type = "bar",
                    title = paste0("DIABLO Loadings - ", tools::toTitleCase(omic)),
                    description = paste0("Feature loadings from DIABLO for ", omic),
                    section = "DIABLO Integration",
                    x_axis = "Feature",
                    y_axis = "Loading"
                )
            }
        }

        # Circos plot
        fig_path <- file.path(plots_dir, "diablo_circos.png")
        if (file.exists(fig_path)) {
            figures[["diablo_circos"]] <- list(
                figure_id = "diablo_circos",
                file_path = fig_path,
                plot_type = "circos",
                title = "DIABLO Circos Plot",
                description = "Circular plot showing correlations between selected features across omics",
                section = "DIABLO Integration",
                x_axis = "NA",
                y_axis = "NA"
            )
        }

        # CV error rate plot
        fig_path <- file.path(plots_dir, "diablo_cv_error.png")
        if (file.exists(fig_path)) {
            figures[["diablo_cv_error"]] <- list(
                figure_id = "diablo_cv_error",
                file_path = fig_path,
                plot_type = "line",
                title = "DIABLO Cross-Validation Error",
                description = "Classification error rate across CV folds and components",
                section = "DIABLO Integration",
                x_axis = "Component",
                y_axis = "Error Rate"
            )
        }
    }

    # ---------------------------------------------------------------------------
    # SNF Figures
    # ---------------------------------------------------------------------------
    if (!is.null(integration_results$snf)) {
        # MDS plot
        fig_path <- file.path(plots_dir, "snf_mds.png")
        if (file.exists(fig_path)) {
            figures[["snf_mds"]] <- list(
                figure_id = "snf_mds",
                file_path = fig_path,
                plot_type = "scatter",
                title = "SNF MDS Plot",
                description = "MDS visualization of fused similarity network, colored by cluster",
                section = "SNF Integration",
                x_axis = "MDS1",
                y_axis = "MDS2"
            )
        }

        # Fused network heatmap
        fig_path <- file.path(plots_dir, "snf_heatmap.png")
        if (file.exists(fig_path)) {
            figures[["snf_heatmap"]] <- list(
                figure_id = "snf_heatmap",
                file_path = fig_path,
                plot_type = "heatmap",
                title = "SNF Fused Network Heatmap",
                description = "Heatmap of the fused similarity network from SNF",
                section = "SNF Integration",
                x_axis = "Sample",
                y_axis = "Sample"
            )
        }
    }

    # ---------------------------------------------------------------------------
    # Concordance Figures
    # ---------------------------------------------------------------------------
    if (!is.null(concordance_results$rna_protein)) {
        # Correlation distribution
        fig_path <- file.path(plots_dir, "rna_protein_concordance.png")
        if (file.exists(fig_path)) {
            figures[["rna_protein_concordance"]] <- list(
                figure_id = "rna_protein_concordance",
                file_path = fig_path,
                plot_type = "histogram",
                title = "RNA-Protein Concordance Distribution",
                description = "Distribution of correlation coefficients between RNA and protein expression",
                section = "Cross-Omics Concordance",
                x_axis = "Pearson Correlation",
                y_axis = "Count"
            )
        }

        # DE scatter plot
        fig_path <- file.path(plots_dir, "rna_protein_de_scatter.png")
        if (file.exists(fig_path)) {
            figures[["rna_protein_de_scatter"]] <- list(
                figure_id = "rna_protein_de_scatter",
                file_path = fig_path,
                plot_type = "scatter",
                title = "RNA vs Protein Fold Change",
                description = "Scatter plot comparing differential expression fold changes between RNA and protein",
                section = "Cross-Omics Concordance",
                x_axis = "RNA Log2 Fold Change",
                y_axis = "Protein Log2 Fold Change"
            )
        }
    }

    # ---------------------------------------------------------------------------
    # Enrichment Figures
    # ---------------------------------------------------------------------------
    for (omic in omics_present) {
        # ORA dotplot
        fig_path <- file.path(plots_dir, paste0(omic, "_ora_dotplot.png"))
        if (file.exists(fig_path)) {
            figures[[paste0("ora_", omic)]] <- list(
                figure_id = paste0("ora_", omic),
                file_path = fig_path,
                plot_type = "dotplot",
                title = paste0("ORA Enrichment - ", tools::toTitleCase(omic)),
                description = paste0("Over-representation analysis results for ", omic),
                section = "Pathway Enrichment",
                x_axis = "-Log10(Adjusted P-value)",
                y_axis = "Pathway"
            )
        }
    }

    # Combined enrichment
    fig_path <- file.path(plots_dir, "combined_enrichment.png")
    if (file.exists(fig_path)) {
        figures[["combined_enrichment"]] <- list(
            figure_id = "combined_enrichment",
            file_path = fig_path,
            plot_type = "dotplot",
            title = "Combined Multi-Omics Enrichment",
            description = "Pathways enriched across multiple omics layers",
            section = "Pathway Enrichment",
            x_axis = "-Log10(Combined P-value)",
            y_axis = "Pathway"
        )
    }

    # Convert to tibble
    if (length(figures) == 0) {
        message("No figures found to generate commentary for")
        return(tibble::tibble(
            figure_id = character(),
            file_path = character(),
            plot_type = character(),
            title = character(),
            description = character(),
            section = character(),
            x_axis = character(),
            y_axis = character()
        ))
    }

    figures_tbl <- dplyr::bind_rows(lapply(figures, tibble::as_tibble))

    message("Found ", nrow(figures_tbl), " figures for commentary")

    return(figures_tbl)
}


#' Generate commentary for all figures
#'
#' @param figures_tbl Table of figures with metadata
#' @param config Pipeline configuration
#' @param mae MultiAssayExperiment object
#' @param foundational_results Results from foundational correlation analysis
#' @param mechanistic_results Results from mechanistic pathway analysis
#' @param integration_results Integration results
#' @param concordance_results Concordance results
#' @param consensus_results Results from consensus analysis
#' @param stability_results Results from stability analysis
#' @param out_dir Output directory for commentary
#' @return A tibble with figure IDs and commentary
generate_all_commentary_multiomics <- function(figures_tbl,
                                    config,
                                    mae,
                                    foundational_results = NULL,
                                    mechanistic_results = NULL,
                                    integration_results = NULL,
                                    concordance_results = NULL,
                                    consensus_results = NULL,
                                    stability_results = NULL,
                                    out_dir) {
    # Check if commentary is enabled
    commentary_config <- config$modes$multiomics$commentary %||% list()
    commentary_enabled <- commentary_config$enabled %||% FALSE

    if (!commentary_enabled) {
        message("Commentary generation is disabled in config")
        return(tibble::tibble(
            figure_id = character(),
            commentary_json = character(),
            backend = character()
        ))
    }

    message("Generating figure commentary...")

    # Create output directory
    dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

    backend <- commentary_config$backend %||% "none"
    message("Using commentary backend: ", backend)

    # Warn about configuration if using AI backend
    if (backend == "claude" && Sys.getenv("ANTHROPIC_API_KEY") == "") {
        message("WARNING: backend is 'claude' but ANTHROPIC_API_KEY is not set.")
        message("  Set it with: Sys.setenv(ANTHROPIC_API_KEY = 'your-key')")
        message("  Will use deterministic fallback commentary if API calls fail.")
    }

    if (backend == "openai" && Sys.getenv("OPENAI_API_KEY") == "") {
        message("WARNING: backend is 'openai' but OPENAI_API_KEY is not set.")
        message("  Set it with: Sys.setenv(OPENAI_API_KEY = 'your-key')")
        message("  Will use deterministic fallback commentary if API calls fail.")
    }

    if (backend == "none") {
        message("INFO: backend is 'none' - using deterministic commentary.")
        message("  To use AI commentary, set commentary.backend to 'claude' or 'openai' in config.yml")
        message("  and ensure the corresponding API key is set as an environment variable.")
    }

    # Convert MAE to legacy format for compatibility
    mae_data <- .mae_to_legacy_commentary(mae)

    # Generate commentary for each figure
    commentary_list <- list()

    for (i in seq_len(nrow(figures_tbl))) {
        fig <- figures_tbl[i, ]
        figure_id <- fig$figure_id

        message("Generating commentary for: ", figure_id)

        # Build context for this figure
        context <- build_figure_context_multiomics(fig, config, mae_data, integration_results, concordance_results)

        # Generate commentary based on backend
        commentary <- tryCatch(
            {
                if (backend == "claude") {
                    run_claude_commentary(fig, context, config, out_dir)
                } else if (backend == "openai") {
                    run_openai_commentary(fig, context, config, out_dir)
                } else {
                    # Data-driven fallback
                    generate_fallback_commentary_multiomics(fig, context, mae_data, integration_results, concordance_results, config)
                }
            },
            error = function(e) {
                message("  AI backend failed, using deterministic fallback")
                # Fall back to deterministic commentary
                generate_fallback_commentary_multiomics(fig, context, mae_data, integration_results, concordance_results, config)
            }
        )

        # Save individual JSON
        json_path <- file.path(out_dir, paste0(figure_id, ".json"))
        write(jsonlite::toJSON(commentary, auto_unbox = TRUE, pretty = TRUE), json_path)

        commentary_list[[figure_id]] <- list(
            figure_id = figure_id,
            commentary_json = as.character(jsonlite::toJSON(commentary, auto_unbox = TRUE)),
            backend = backend
        )
    }

    # Combine into tibble
    commentary_tbl <- dplyr::bind_rows(commentary_list)

    # Save combined CSV
    combined_path <- file.path(out_dir, "all_commentary.csv")
    readr::write_csv(commentary_tbl, combined_path)

    # Save combined JSON
    all_commentary <- lapply(commentary_list, function(x) {
        jsonlite::fromJSON(x$commentary_json)
    })
    write(
        jsonlite::toJSON(all_commentary, auto_unbox = TRUE, pretty = TRUE),
        file.path(out_dir, "all_commentary.json")
    )

    message("Commentary saved to: ", out_dir)

    return(commentary_tbl)
}


#' Convert MAE to legacy format for commentary
#' @param mae MultiAssayExperiment object
#' @return Legacy-format list
.mae_to_legacy_commentary <- function(mae) {
    harmonized_omics <- lapply(names(mae@ExperimentList), function(nm) {
        exp_data <- mae@ExperimentList[[nm]]
        list(
            normalized_matrix = as.matrix(SummarizedExperiment::assay(exp_data)),
            feature_annotation = as.data.frame(SummarizedExperiment::rowData(exp_data))
        )
    })
    names(harmonized_omics) <- names(mae@ExperimentList)

    list(
        mae = mae,
        harmonized_omics = harmonized_omics,
        metadata = as.data.frame(SummarizedExperiment::colData(mae)),
        common_samples = colnames(mae),
        config = list(design = list(condition_column = "condition"))
    )
}


#' Build context for a specific figure
#'
#' @param fig Figure row from figures_tbl
#' @param config Configuration
#' @param mae_data MAE data (legacy format)
#' @param integration_results Integration results
#' @param concordance_results Concordance results
#' @return List with context information
build_figure_context_multiomics <- function(fig, config, mae_data, integration_results, concordance_results) {
    context <- list(
        plot_type = fig$plot_type,
        title = fig$title,
        description = fig$description,
        section = fig$section,
        x_axis = fig$x_axis,
        y_axis = fig$y_axis,
        organism = config$global$organism,
        n_samples = length(mae_data$common_samples),
        omics_present = paste(names(mae_data$harmonized_omics), collapse = ", "),
        condition_col = config$design$condition_column,
        design_formula = config$design$design_formula
    )

    figure_id <- fig$figure_id

    # Add MOFA-specific context
    if (grepl("^mofa_", figure_id) && !is.null(integration_results$mofa)) {
        mofa <- integration_results$mofa
        if (!is.null(mofa$variance_explained)) {
            context$mofa_total_variance <- sum(mofa$variance_explained$total)
            context$mofa_n_factors <- ncol(mofa$variance_explained)
        }
    }

    # Add DIABLO-specific context
    if (grepl("^diablo_", figure_id) && !is.null(integration_results$diablo)) {
        diablo <- integration_results$diablo
        if (!is.null(diablo$cv_error)) {
            context$diablo_cv_error <- min(diablo$cv_error)
        }
        if (!is.null(diablo$selected_features)) {
            context$diablo_n_features <- sum(sapply(diablo$selected_features, length))
        }
    }

    # Add SNF-specific context
    if (grepl("^snf_", figure_id) && !is.null(integration_results$snf)) {
        snf <- integration_results$snf
        if (!is.null(snf$nmi)) {
            context$snf_nmi <- snf$nmi
        }
        if (!is.null(snf$n_clusters)) {
            context$snf_n_clusters <- snf$n_clusters
        }
    }

    # Add concordance-specific context
    if (grepl("concordance|de_scatter", figure_id) && !is.null(concordance_results$rna_protein)) {
        rp <- concordance_results$rna_protein
        if (!is.null(rp$summary)) {
            context$concordance_mean_cor <- rp$summary$mean_cor
            context$concordance_n_genes <- rp$summary$n_genes
            context$concordance_pct_positive <- rp$summary$pct_positive
        }
    }

    return(context)
}


#' Run Claude Vision API for commentary
run_claude_commentary <- function(fig, context, config, output_dir) {
    # Pre-flight check: script exists
    script_path <- "scripts/figure_commentary_claude.py"
    if (!file.exists(script_path)) {
        warning("Claude commentary script not found: ", script_path, "\n  Falling back to deterministic commentary.")
        stop("Script not found: ", script_path)
    }

    # Pre-flight check: API key
    if (Sys.getenv("ANTHROPIC_API_KEY") == "") {
        warning("ANTHROPIC_API_KEY not set. Cannot use Claude API.\n  Falling back to deterministic commentary.")
        stop("ANTHROPIC_API_KEY environment variable not set")
    }

    # Write context to temp file
    context_file <- tempfile(fileext = ".json")
    write(jsonlite::toJSON(context, auto_unbox = TRUE), context_file)
    on.exit(unlink(context_file), add = TRUE)

    out_file <- file.path(output_dir, paste0(fig$figure_id, "_claude.json"))

    # Build command
    commentary_config <- config$modes$multiomics$commentary %||% list()
    model <- commentary_config$claude_model %||% "claude-sonnet-4-20250514"
    max_tokens <- commentary_config$max_tokens %||% 1500
    max_retries <- commentary_config$max_retries %||% 2

    cmd <- sprintf(
        "python3 '%s' --image '%s' --figure_id '%s' --context_json '%s' --out_json '%s' --model '%s' --max_tokens %d --max_retries %d 2>&1",
        script_path, fig$file_path, fig$figure_id, context_file, out_file, model, max_tokens, max_retries
    )

    message("  Calling Claude API for ", fig$figure_id, "...")

    # Execute and capture both stdout and stderr
    exit_code <- system(cmd, intern = FALSE, ignore.stdout = FALSE, ignore.stderr = FALSE)

    # Check exit code
    if (exit_code != 0) {
        warning("Claude commentary script failed with exit code ", exit_code, "\n  Figure: ", fig$figure_id, "\n  Falling back to deterministic commentary.")

        # Try to read the error JSON if it exists
        if (file.exists(out_file)) {
            error_json <- tryCatch(jsonlite::fromJSON(out_file), error = function(e) NULL)
            if (!is.null(error_json) && !is.null(error_json$limitations)) {
                warning("  Error from Python: ", error_json$limitations)
            }
        }

        stop("Python script exited with code ", exit_code)
    }

    # Read and return the generated commentary
    if (file.exists(out_file)) {
        commentary <- tryCatch(
            jsonlite::fromJSON(out_file),
            error = function(e) {
                warning("Failed to parse Claude output JSON: ", e$message, "\n  Falling back to deterministic commentary.")
                stop("JSON parse error: ", e$message)
            }
        )
    } else {
        warning("Claude commentary script did not produce output file: ", out_file, "\n  Falling back to deterministic commentary.")
        stop("Claude commentary script did not produce output")
    }

    message("  Claude commentary generated successfully")

    return(commentary)
}


#' Run OpenAI Vision API for commentary
run_openai_commentary <- function(fig, context, config, output_dir) {
    # Pre-flight check: script exists
    script_path <- "scripts/figure_commentary_openai.py"
    if (!file.exists(script_path)) {
        warning("OpenAI commentary script not found: ", script_path, "\n  Falling back to deterministic commentary.")
        stop("Script not found: ", script_path)
    }

    # Pre-flight check: API key
    if (Sys.getenv("OPENAI_API_KEY") == "") {
        warning("OPENAI_API_KEY not set. Cannot use OpenAI API.\n  Falling back to deterministic commentary.")
        stop("OPENAI_API_KEY environment variable not set")
    }

    # Write context to temp file
    context_file <- tempfile(fileext = ".json")
    write(jsonlite::toJSON(context, auto_unbox = TRUE), context_file)
    on.exit(unlink(context_file), add = TRUE)

    out_file <- file.path(output_dir, paste0(fig$figure_id, "_openai.json"))

    # Build command
    commentary_config <- config$modes$multiomics$commentary %||% list()
    model <- commentary_config$openai_model %||% "gpt-4o"
    max_tokens <- commentary_config$max_tokens %||% 1500
    max_retries <- commentary_config$max_retries %||% 2

    cmd <- sprintf(
        "python3 '%s' --image '%s' --figure_id '%s' --context_json '%s' --out_json '%s' --model '%s' --max_tokens %d --max_retries %d 2>&1",
        script_path, fig$file_path, fig$figure_id, context_file, out_file, model, max_tokens, max_retries
    )

    message("  Calling OpenAI API for ", fig$figure_id, "...")

    # Execute and capture both stdout and stderr
    exit_code <- system(cmd, intern = FALSE, ignore.stdout = FALSE, ignore.stderr = FALSE)

    # Check exit code
    if (exit_code != 0) {
        warning("OpenAI commentary script failed with exit code ", exit_code, "\n  Figure: ", fig$figure_id, "\n  Falling back to deterministic commentary.")

        # Try to read the error JSON if it exists
        if (file.exists(out_file)) {
            error_json <- tryCatch(jsonlite::fromJSON(out_file), error = function(e) NULL)
            if (!is.null(error_json) && !is.null(error_json$limitations)) {
                warning("  Error from Python: ", error_json$limitations)
            }
        }

        stop("Python script exited with code ", exit_code)
    }

    # Read and return the generated commentary
    if (file.exists(out_file)) {
        commentary <- tryCatch(
            jsonlite::fromJSON(out_file),
            error = function(e) {
                warning("Failed to parse OpenAI output JSON: ", e$message, "\n  Falling back to deterministic commentary.")
                stop("JSON parse error: ", e$message)
            }
        )
    } else {
        warning("OpenAI commentary script did not produce output file: ", out_file, "\n  Falling back to deterministic commentary.")
        stop("OpenAI commentary script did not produce output")
    }

    message("  OpenAI commentary generated successfully")

    return(commentary)
}


#' Create placeholder commentary on error
create_placeholder_commentary_multiomics <- function(figure_id, error_message) {
    list(
        figure_id = figure_id,
        title = "Commentary Generation Failed",
        what_is_this = "Unable to generate automated commentary for this figure.",
        observations = list(),
        issues_checks = list(),
        next_steps = list(),
        confidence = "none",
        limitations = paste("Error:", error_message)
    )
}


#' Get static explanation for a plot type
#'
#' @param plot_type The type of plot
#' @return A string with educational explanation
get_static_explanation <- function(plot_type) {
    explanations <- list(
        "mofa_variance_heatmap" = "MOFA2 (Multi-Omics Factor Analysis v2) identifies latent factors that capture shared variation across multiple omics. The variance explained heatmap shows how much each factor contributes to each omics layer, helping identify factors driven by shared vs. omics-specific signals.",
        "mofa_factors" = "MOFA factor plots show samples in reduced dimension space defined by latent factors. Unlike PCA on concatenated data, MOFA learns factors that explicitly model the multi-view structure. Separation by condition suggests the factors capture biologically meaningful variation.",
        "diablo_sample" = "DIABLO (Data Integration Analysis for Biomarker discovery using Latent variable approaches for Omics studies) is a supervised multi-omics method. It finds sparse multi-omics signatures that maximize classification accuracy while selecting interpretable feature sets.",
        "diablo_circos" = "Circos plots visualize the correlation structure between features selected by DIABLO across omics layers. Strong connections between RNA-protein pairs may indicate transcriptional control, while connections to metabolites suggest functional relationships.",
        "snf_mds" = "Similarity Network Fusion (SNF) constructs patient similarity networks for each omics type and fuses them into a unified network. Unlike supervised methods, SNF discovers natural patient subgroups that may reveal novel disease subtypes.",
        "concordance" = "RNA-protein concordance measures how well mRNA abundance predicts protein levels. While positive correlation is expected, post-transcriptional regulation, protein stability, and technical factors typically result in correlations of 0.3-0.6 in well-matched samples.",
        "enrichment" = "Over-representation analysis (ORA) tests whether significantly changed features are enriched in biological pathways beyond what's expected by chance. Multi-omics enrichment combines evidence across layers for more robust pathway identification."
    )

    # Match by partial key
    for (key in names(explanations)) {
        if (grepl(key, plot_type, ignore.case = TRUE)) {
            return(explanations[[key]])
        }
    }

    return("This figure is part of the multi-omics integration analysis pipeline.")
}
