# R/core/12_commentary.R
# AI-generated figure commentary for pipeline reports
# Supports Claude Code CLI, Claude API, OpenAI API, and data-driven fallback
#
# Figure interpretation guidance is informed by domain knowledge from:
#   K-Dense AI "claude-scientific-skills" (MIT License)
#   https://github.com/K-Dense-AI/claude-scientific-skills
#   Skills used: scientific-writing, scientific-critical-thinking,
#                scientific-visualization, pydeseq2
#
# AI commentary is generated by Claude (Anthropic) via Claude Code CLI
# or the Anthropic API. See: https://claude.ai/claude-code
#
# Credit: K-Dense AI for scientific domain knowledge templates;
#         Anthropic for the Claude language model powering the analysis.

# --------------------------------------------------------------------------
# Figure discovery
# --------------------------------------------------------------------------

#' Discover all figure files from the RNA output directory
#'
#' Scans Diagnostic_plots/, DE_plots/, and Enrichment/plots/ directories
#' for PNG files and builds a metadata table.
#'
#' @param out_dir  RNA output directory (e.g. .../rna)
#' @param config   Full pipeline config
#' @return Data frame with figure_id, filepath, plot_type, section, title, etc.
discover_figures <- function(out_dir, config = NULL) {

    diag_dir   <- file.path(out_dir, "Diagnostic_plots")
    qc_post    <- file.path(diag_dir, "DE_plots")
    enrich_plt <- file.path(out_dir, "Enrichment", "plots")

    figures <- list()

    add_if_exists <- function(id, filename, dir, plot_type, section, title, desc,
                               x_axis = NA, y_axis = NA) {
        fp <- file.path(dir, filename)
        if (file.exists(fp)) {
            figures[[id]] <<- data.frame(
                figure_id   = id,
                filepath    = fp,
                plot_type   = plot_type,
                section     = section,
                title       = title,
                description = desc,
                x_axis      = x_axis,
                y_axis      = y_axis,
                contrast    = NA_character_,
                stringsAsFactors = FALSE
            )
        }
    }

    # --- QC / Pre-DE plots ---
    add_if_exists("raw_boxplot", "raw_boxplot.png", diag_dir,
                  "boxplot", "QC", "Raw Expression Boxplot",
                  "Per-sample raw expression distribution before normalization",
                  "Sample", "log2(raw counts + 1)")

    add_if_exists("norm_boxplot", "norm_boxplot.png", diag_dir,
                  "boxplot", "QC", "Normalized Expression Boxplot",
                  "Per-sample normalized expression distribution (TMMlogCPM)",
                  "Sample", "log2(CPM)")

    add_if_exists("density_plot", "rna_histograms_summary.png", diag_dir,
                  "density", "QC", "Expression Density Plot",
                  "Per-sample expression distribution as density curves after normalization",
                  "Expression (log2 CPM)", "Density")

    add_if_exists("pca_plot", "PCA_PC1.vs.PC2.png", diag_dir,
                  "scatter", "QC", "PCA Plot — PC1 vs PC2",
                  "Principal component analysis of samples — first two components",
                  "PC1", "PC2")

    add_if_exists("pca_plot_13", "PCA_PC1.vs.PC3.png", diag_dir,
                  "scatter", "QC", "PCA Plot — PC1 vs PC3",
                  "Principal component analysis of samples — first and third components",
                  "PC1", "PC3")

    add_if_exists("sample_correlation", "sample_correlation_heatmap.png", diag_dir,
                  "heatmap", "QC", "Sample-to-Sample Correlation",
                  "Pearson correlation matrix between samples based on normalized expression",
                  "Samples", "Samples")

    add_if_exists("sample_distance", "sample_distance_heatmap.png", diag_dir,
                  "heatmap", "QC", "Sample-to-Sample Distance",
                  "Euclidean distance matrix between samples based on normalized expression",
                  "Samples", "Samples")

    add_if_exists("expr_heatmap", "samples_rna_heatmap.png", diag_dir,
                  "heatmap", "QC", "Expression Heatmap",
                  "Expression patterns of top variable genes across samples with hierarchical clustering",
                  "Samples", "Genes")

    # Helper: build a list of figure-row data.frames from a directory scan.
    # fid_prefix is used for the figure_id; type is the plot_type field.
    # cn_fn extracts the contrast/label from the basename.
    make_contrast_rows <- function(dir, pattern, fid_prefix, type, section,
                                    title_pfx, desc, x_axis, y_axis, cn_fn) {
        if (!dir.exists(dir)) return(list())
        files <- list.files(dir, pattern = pattern, full.names = TRUE)
        lapply(files, function(f) {
            cn  <- cn_fn(basename(f))
            fid <- paste0(fid_prefix, "_", cn)
            data.frame(figure_id = fid, filepath = f, plot_type = type,
                       section = section, title = paste0(title_pfx, gsub("_", " ", cn)),
                       description = desc, x_axis = x_axis, y_axis = y_axis,
                       contrast = cn, stringsAsFactors = FALSE)
        })
    }

    # --- Volcano, MA, DE heatmap (per contrast) + Pathway dotplots ---
    contrast_rows <- c(
        make_contrast_rows(qc_post, "^volcano_.*\\.png$", "volcano", "volcano",
            "Differential Expression", "Volcano Plot: ",
            "Statistical significance vs fold change for all genes in this contrast",
            "log2 Fold Change", "-log10(adjusted p-value)",
            function(f) gsub("^volcano_|\\.png$", "", f)),
        make_contrast_rows(qc_post, "^ma_.*\\.png$", "ma", "ma_plot",
            "Differential Expression", "MA Plot: ",
            "Mean-difference plot: fold change vs average expression for all genes",
            "log10(Mean Expression)", "log2 Fold Change",
            function(f) gsub("^ma_|\\.png$", "", f)),
        make_contrast_rows(qc_post, "^heatmap_top_.*\\.png$", "heatmap_top", "heatmap",
            "Differential Expression", "Top DE Genes Heatmap: ",
            "Expression patterns of top differentially expressed genes across all samples",
            "Samples", "Genes",
            function(f) gsub("^heatmap_top_|\\.png$", "", f)),
        make_contrast_rows(enrich_plt, "\\.png$", "pathway", "dotplot",
            "Pathway Analysis", "Pathway Enrichment: ",
            "Enriched pathways from gene set enrichment analysis",
            "Enrichment Score", "Pathway",
            function(f) gsub("^pathway_|\\.png$", "", f))
    )
    for (row in contrast_rows) figures[[row$figure_id]] <- row

    if (length(figures) == 0) {
        message("No figures discovered for commentary")
        return(data.frame(
            figure_id = character(), filepath = character(),
            plot_type = character(), section = character(),
            title = character(), description = character(),
            x_axis = character(), y_axis = character(),
            contrast = character(), stringsAsFactors = FALSE
        ))
    }

    figures_tbl <- do.call(rbind, figures)
    rownames(figures_tbl) <- NULL
    message("Discovered ", nrow(figures_tbl), " figures for commentary")
    figures_tbl
}


# --------------------------------------------------------------------------
# Context building — enriched with experiment data
# --------------------------------------------------------------------------

#' Build rich context information for a figure
#'
#' @param fig         Row from figures_tbl
#' @param config      Pipeline config
#' @param de_summary  DE summary counts data frame (optional)
#' @param extra_data  Named list with enriched data: top_genes, pca_variance,
#'                    groups, n_samples, norm_method, de_method, de_cutoffs
#' @return List with context
build_figure_context <- function(fig, config, de_summary = NULL, extra_data = NULL) {
    rna_cfg <- config$modes$rna

    context <- list(
        figure_id   = fig$figure_id,
        plot_type   = fig$plot_type,
        section     = fig$section,
        title       = fig$title,
        description = fig$description,
        x_axis      = fig$x_axis,
        y_axis      = fig$y_axis,
        contrast    = fig$contrast
    )

    # --- Experiment context ---
    context$organism     <- rna_cfg$annotation$organism %||% "unknown"
    context$group_col    <- rna_cfg$filtering$group_col %||% rna_cfg$effects$color
    context$project_name <- config$project$name

    # --- Enriched data ---
    if (!is.null(extra_data)) {
        # Groups and sample counts
        context$groups    <- extra_data$groups
        context$n_samples <- extra_data$n_samples

        # Methods
        context$norm_method <- extra_data$norm_method
        context$de_method   <- extra_data$de_method
        context$de_cutoffs  <- extra_data$de_cutoffs

        # PCA variance explained
        if (!is.null(extra_data$pca_variance)) {
            context$pca_var_pc1 <- extra_data$pca_variance[1]
            context$pca_var_pc2 <- extra_data$pca_variance[2]
            if (length(extra_data$pca_variance) >= 3) {
                context$pca_var_pc3 <- extra_data$pca_variance[3]
            }
        }

        # Top DE genes/proteins for the current contrast
        if (!is.na(fig$contrast) && !is.null(extra_data$top_genes)) {
            # Try exact match first, then partial (fig contrast may have suffixes)
            tg <- extra_data$top_genes[[fig$contrast]]
            if (is.null(tg)) {
                for (cn in names(extra_data$top_genes)) {
                    if (grepl(cn, fig$contrast, fixed = TRUE)) {
                        tg <- extra_data$top_genes[[cn]]
                        break
                    }
                }
            }
            if (!is.null(tg)) {
                context$top_genes <- tg
            }
        }

        # Domain-specific overrides (e.g. "proteomics")
        if (!is.null(extra_data$domain_label)) {
            context$domain_label <- extra_data$domain_label
        }
        if (!is.null(extra_data$domain_guidance)) {
            context$domain_guidance <- extra_data$domain_guidance
        }
    }

    # --- DE summary counts ---
    if (!is.null(de_summary) && !is.na(fig$contrast)) {
        # Match: fig$contrast contains de_summary$contrast, or vice versa
        row <- de_summary[
            sapply(de_summary$contrast, function(cn) grepl(cn, fig$contrast, fixed = TRUE)),
        , drop = FALSE]
        if (nrow(row) > 0) {
            row <- row[1, ]
            context$de_significant <- row$significant %||% row$total_de %||% row$total
            context$de_up   <- row$up %||% row$up_regulated
            context$de_down <- row$down %||% row$down_regulated
            context$de_total_tested <- row$total_tested %||% row$total
        }
    }

    context
}


# --------------------------------------------------------------------------
# Figure-type-specific interpretation guidance
# (Informed by K-Dense scientific-skills: scientific-visualization,
#  scientific-critical-thinking, pydeseq2, scientific-writing)
# --------------------------------------------------------------------------

#' Build figure-type-specific analysis guidance for the AI prompt
#' @param context Context list from build_figure_context()
#' @return Character string with interpretation instructions
build_figure_guidance <- function(context) {
    pt <- context$plot_type
    fid <- context$figure_id
    feature_term <- if (identical(context$domain_label, "proteomics")) "proteins" else "genes"

    # PCA plots
    if (pt == "scatter" && grepl("pca", fid, ignore.case = TRUE)) {
        var_info <- ""
        if (!is.null(context$pca_var_pc1)) {
            var_info <- sprintf(
                "\nPC1 explains %.1f%% of variance, PC2 explains %.1f%% of variance.",
                context$pca_var_pc1, context$pca_var_pc2
            )
            if (grepl("PC3|13", fid) && !is.null(context$pca_var_pc3)) {
                var_info <- sprintf(
                    "\nPC1 explains %.1f%% of variance, PC3 explains %.1f%% of variance.",
                    context$pca_var_pc1, context$pca_var_pc3
                )
            }
        }
        group_info <- ""
        if (!is.null(context$groups)) {
            group_info <- sprintf(
                "\nExperimental groups: %s. Total samples: %s.",
                paste(context$groups, collapse = ", "),
                context$n_samples %||% "unknown"
            )
        }
        return(paste0(
            "INTERPRETATION GUIDANCE FOR PCA PLOT:",
            var_info, group_info,
            "\n- Assess whether samples separate by experimental condition (biological signal) vs batch or other technical artifacts.",
            "\n- Describe the spatial arrangement: do groups form distinct clusters? Is there overlap?",
            "\n- If PC1 explains >40% variance, discuss what might drive this dominant axis.",
            "\n- Identify any outlier samples that fall far from their group centroid.",
            "\n- Comment on within-group dispersion (tight clusters = consistent replicates).",
            "\n- If groups do NOT separate, explain what this implies (subtle effect, high biological variability, or insufficient sample size).",
            "\n- Relate the variance explained by each PC to the biology: a PC that separates treatment groups likely captures the treatment effect."
        ))
    }

    # Boxplots
    if (pt == "boxplot") {
        norm_info <- ""
        if (!is.null(context$norm_method)) {
            norm_info <- sprintf("\nNormalization method: %s.", context$norm_method)
        }
        if (grepl("raw", fid)) {
            return(paste0(
                "INTERPRETATION GUIDANCE FOR RAW EXPRESSION BOXPLOT:",
                "\n- This shows per-sample expression distributions BEFORE normalization.",
                "\n- Assess library-size variation: samples with noticeably lower/higher median may have different sequencing depth.",
                "\n- Large differences in box height indicate variable dynamic range across samples.",
                "\n- These raw differences should be corrected after normalization."
            ))
        }
        return(paste0(
            "INTERPRETATION GUIDANCE FOR NORMALIZED EXPRESSION BOXPLOT:", norm_info,
            "\n- After normalization, all sample boxes should have similar median and interquartile range.",
            "\n- Remaining differences may indicate biological variation or incomplete batch correction.",
            "\n- Samples with notably different distributions may be outliers."
        ))
    }

    # Density plots
    if (pt == "density") {
        return(paste0(
            "INTERPRETATION GUIDANCE FOR EXPRESSION DENSITY PLOT:",
            "\n- Each curve represents one sample's expression distribution.",
            "\n- After normalization, curves should largely overlap.",
            "\n- Bimodal distributions are common (low/no expression peak + expressed ", feature_term, " peak).",
            "\n- Samples with shifted or differently shaped curves may indicate quality issues or biological differences."
        ))
    }

    # Correlation heatmap
    if (pt == "heatmap" && grepl("correlation", fid)) {
        return(paste0(
            "INTERPRETATION GUIDANCE FOR SAMPLE CORRELATION HEATMAP:",
            "\n- Shows Pearson correlation between all sample pairs based on genome-wide expression.",
            "\n- Biological replicates should have correlation >0.9 (often >0.95).",
            "\n- Clear block-diagonal structure with high within-group and lower between-group correlation indicates strong condition effects.",
            "\n- A sample with low correlation to all others (including its own group) is a potential outlier.",
            "\n- If samples cluster by batch rather than condition, batch correction may be needed."
        ))
    }

    # Distance heatmap
    if (pt == "heatmap" && grepl("distance", fid)) {
        return(paste0(
            "INTERPRETATION GUIDANCE FOR SAMPLE DISTANCE HEATMAP:",
            "\n- Shows Euclidean distance between samples based on expression profiles.",
            "\n- Low distance (dark) between replicates indicates consistency.",
            "\n- Hierarchical clustering dendrograms should group replicates from the same condition together.",
            "\n- Cross-condition distances should be larger than within-condition distances."
        ))
    }

    # Expression heatmap
    if (pt == "heatmap" && grepl("expr_heatmap", fid)) {
        return(paste0(
            "INTERPRETATION GUIDANCE FOR EXPRESSION HEATMAP:",
            "\n- Shows z-score-scaled expression of top variable ", feature_term, " across all samples.",
            "\n- Row clustering reveals co-expressed gene modules.",
            "\n- Column clustering should ideally group samples by experimental condition.",
            "\n- Identify blocks of ", feature_term, " that are consistently up or down in specific conditions.",
            "\n- This gives a global overview of transcriptomic differences between conditions."
        ))
    }

    # Volcano plot
    if (pt == "volcano") {
        de_info <- ""
        if (!is.null(context$de_significant)) {
            de_info <- sprintf(
                "\nDE statistics: %s significant %s (%s up, %s down) out of %s tested.",
                context$de_significant, feature_term,
                context$de_up %||% "?",
                context$de_down %||% "?",
                context$de_total_tested %||% "?"
            )
        }
        cutoff_info <- ""
        if (!is.null(context$de_cutoffs)) {
            cutoff_info <- sprintf(
                "\nCutoffs: adjusted p-value <= %s, |linear FC| >= %s.",
                context$de_cutoffs$p_cutoff %||% "0.05",
                context$de_cutoffs$fc_cutoff %||% "1.5"
            )
        }
        gene_info <- ""
        if (!is.null(context$top_genes)) {
            tg <- context$top_genes
            top_up <- tg[tg$direction == "up", ]
            top_dn <- tg[tg$direction == "down", ]
            if (nrow(top_up) > 0) {
                gene_info <- paste0(gene_info, sprintf(
                    "\nTop up-regulated %s: %s", feature_term,
                    paste(sprintf("%s (log2FC=%.1f, padj=%.1e)",
                          top_up$gene, top_up$log2FC, top_up$padj),
                          collapse = "; ")
                ))
            }
            if (nrow(top_dn) > 0) {
                gene_info <- paste0(gene_info, sprintf(
                    "\nTop down-regulated %s: %s", feature_term,
                    paste(sprintf("%s (log2FC=%.1f, padj=%.1e)",
                          top_dn$gene, top_dn$log2FC, top_dn$padj),
                          collapse = "; ")
                ))
            }
        }
        return(paste0(
            "INTERPRETATION GUIDANCE FOR VOLCANO PLOT:",
            "\nContrast: ", context$contrast %||% "unknown",
            de_info, cutoff_info, gene_info,
            "\n- The x-axis shows log2 fold change (effect size); the y-axis shows -log10 adjusted p-value (statistical significance).",
            "\n- Dashed lines indicate significance cutoffs.",
            "\n- Describe the overall pattern: symmetric (balanced up/down) or asymmetric?",
            "\n- Name the most prominent ", feature_term, " if visible in the plot or provided in the data above.",
            "\n- For named ", feature_term, ", briefly mention their known biological function if relevant to the organism (",
            context$organism %||% "unknown", ").",
            "\n- Comment on the proportion of significant ", feature_term, " relative to total tested.",
            "\n- If many ", feature_term, " cluster near the cutoff boundary, note that these are borderline results."
        ))
    }

    # MA plot
    if (pt == "ma_plot") {
        return(paste0(
            "INTERPRETATION GUIDANCE FOR MA PLOT:",
            "\nContrast: ", context$contrast %||% "unknown",
            "\n- The x-axis shows average expression (baseMean on log10 scale); y-axis shows log2 fold change.",
            "\n- After proper normalization, the cloud of non-significant ", feature_term, " should be centered at log2FC = 0.",
            "\n- Asymmetry or trend in the cloud suggests normalization issues.",
            "\n- Lowly expressed ", feature_term, " (left side) have higher fold-change variance — this is expected.",
            "\n- Significant ", feature_term, " (colored) scattered at high expression levels are the most reliable DE calls.",
            "\n- Comment on whether normalization appears adequate based on the overall cloud shape."
        ))
    }

    # Top DE heatmap
    if (pt == "heatmap" && grepl("heatmap_top", fid)) {
        gene_info <- ""
        if (!is.null(context$top_genes)) {
            top_names <- head(context$top_genes$gene, 10)
            gene_info <- sprintf("\nTop DE %s include: %s", feature_term, paste(top_names, collapse = ", "))
        }
        return(paste0(
            "INTERPRETATION GUIDANCE FOR TOP DE ", toupper(feature_term), " HEATMAP:",
            "\nContrast: ", context$contrast %||% "unknown", gene_info,
            "\n- Shows row-scaled (z-score) expression of the top differentially expressed ", feature_term, ".",
            "\n- Check if the heatmap clearly separates the two conditions in this contrast.",
            "\n- Identify co-regulated clusters (groups of ", feature_term, " with similar patterns).",
            "\n- Describe the overall pattern: are most ", feature_term, " up in one condition vs the other, or mixed?",
            "\n- If names are visible, mention any with known biological relevance."
        ))
    }

    # Pathway dotplot
    if (pt == "dotplot") {
        return(paste0(
            "INTERPRETATION GUIDANCE FOR PATHWAY ENRICHMENT PLOT:",
            "\nContrast: ", context$contrast %||% "unknown",
            "\n- Dot size typically indicates the number of ", feature_term, " in the gene set that overlap with DE ", feature_term, ".",
            "\n- Color indicates statistical significance (p-value or adjusted p-value).",
            "\n- Identify the top enriched pathways and their biological relevance to the experiment.",
            "\n- Group related pathways into biological themes (e.g., immune response, metabolism, cell cycle).",
            "\n- Note whether enrichment is predominantly in up-regulated or down-regulated ", feature_term, ".",
            "\n- Comment on whether the enriched pathways make biological sense given the organism (",
            context$organism %||% "unknown", ") and experimental context."
        ))
    }

    # Generic fallback guidance
    paste0(
        "INTERPRETATION GUIDANCE:",
        "\n- Describe what the figure shows in precise scientific language.",
        "\n- Identify the main patterns visible in the data.",
        "\n- Note any potential quality issues or anomalies.",
        "\n- Relate findings to the experimental design."
    )
}


# --------------------------------------------------------------------------
# Main generation loop
# --------------------------------------------------------------------------

#' Generate commentary for all discovered figures
#'
#' @param figures_tbl  Figures metadata from discover_figures()
#' @param config       Pipeline config
#' @param de_summary   DE summary data frame (optional)
#' @param extra_data   Enriched data list from mod_rnaseq_commentary()
#' @param output_dir   Directory for commentary output files
#' @return Named list of commentary objects (keyed by figure_id)
generate_all_commentary <- function(figures_tbl, config, de_summary = NULL,
                                     extra_data = NULL, output_dir = NULL) {

    dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

    rna_cfg <- config$modes$rna
    commentary_cfg <- rna_cfg$commentary %||% list()

    enabled <- isTRUE(commentary_cfg$enabled)
    backend <- commentary_cfg$backend %||% "none"

    if (!enabled) {
        message("Commentary disabled. Using data-driven fallback.")
        backend <- "none"
    }

    # Check API key availability for API backends
    if (backend == "claude" && Sys.getenv("ANTHROPIC_API_KEY") == "") {
        warning("ANTHROPIC_API_KEY not set. Falling back to data-driven commentary.")
        backend <- "none"
    }
    if (backend == "openai" && Sys.getenv("OPENAI_API_KEY") == "") {
        warning("OPENAI_API_KEY not set. Falling back to data-driven commentary.")
        backend <- "none"
    }
    # claude-code backend: check that 'claude' CLI is available
    if (backend == "claude-code" && Sys.which("claude") == "") {
        warning("'claude' CLI not found in PATH. Falling back to data-driven commentary.")
        backend <- "none"
    }

    commentary_list <- list()

    for (i in seq_len(nrow(figures_tbl))) {
        fig <- figures_tbl[i, ]
        message("Generating commentary for: ", fig$figure_id)

        if (!file.exists(fig$filepath)) {
            message("  Warning: figure not found: ", fig$filepath)
            commentary_list[[fig$figure_id]] <- create_placeholder_commentary(
                fig$figure_id, reason = "Figure file not found"
            )
            next
        }

        context <- build_figure_context(fig, config, de_summary, extra_data)

        if (backend == "claude-code") {
            commentary <- run_claude_code_commentary(
                image_path = fig$filepath,
                figure_id  = fig$figure_id,
                context    = context,
                config     = commentary_cfg,
                output_dir = output_dir
            )
        } else if (backend %in% c("claude", "openai")) {
            commentary <- run_vision_commentary(
                image_path = fig$filepath,
                figure_id  = fig$figure_id,
                context    = context,
                backend    = backend,
                config     = commentary_cfg,
                output_dir = output_dir
            )
        } else {
            commentary <- generate_fallback_commentary(fig, context, de_summary)
        }

        commentary_list[[fig$figure_id]] <- commentary

        # Save individual JSON
        if (!is.null(output_dir)) {
            json_path <- file.path(output_dir, paste0(fig$figure_id, "_commentary.json"))
            jsonlite::write_json(commentary, json_path, auto_unbox = TRUE, pretty = TRUE)
        }
    }

    # Save combined JSON
    if (!is.null(output_dir) && length(commentary_list) > 0) {
        combined_path <- file.path(output_dir, "commentary_all.json")
        jsonlite::write_json(commentary_list, combined_path, auto_unbox = TRUE, pretty = TRUE)
        message("Saved combined commentary to: ", combined_path)
    }

    commentary_list
}


# --------------------------------------------------------------------------
# Claude Code CLI backend (enhanced prompt with K-Dense knowledge)
# --------------------------------------------------------------------------

#' Run commentary via Claude Code CLI
#'
#' Uses `claude --print` with enriched, figure-type-specific prompts informed
#' by K-Dense scientific-skills (scientific-writing, scientific-critical-thinking,
#' pydeseq2, scientific-visualization).
#'
#' @param image_path  Path to figure image
#' @param figure_id   Figure identifier
#' @param context     Context list from build_figure_context()
#' @param config      Commentary config section
#' @param output_dir  Output directory
#' @return Commentary list
run_claude_code_commentary <- function(image_path, figure_id, context,
                                        config, output_dir) {

    output_json <- file.path(output_dir, paste0(figure_id, "_commentary.json"))

    # Build the experiment context string
    context_str <- paste0(
        "Figure: ", context$title %||% figure_id, "\n",
        "Plot type: ", context$plot_type %||% "unknown", "\n",
        "Section: ", context$section %||% "", "\n",
        "Organism: ", context$organism %||% "unknown", "\n",
        "Project: ", context$project_name %||% "", "\n",
        if (!is.null(context$groups)) paste0(
            "Experimental groups: ", paste(context$groups, collapse = ", "), "\n"
        ) else "",
        if (!is.null(context$n_samples)) paste0(
            "Total samples: ", context$n_samples, "\n"
        ) else "",
        if (!is.null(context$norm_method)) paste0(
            "Normalization: ", context$norm_method, "\n"
        ) else "",
        if (!is.null(context$de_method)) paste0(
            "DE method: ", context$de_method, "\n"
        ) else ""
    )

    # Get figure-type-specific interpretation guidance
    guidance <- build_figure_guidance(context)
    if (!is.null(context$domain_guidance)) {
        guidance <- paste0(guidance, "\n\n", context$domain_guidance)
    }

    # JSON schema for structured output
    json_schema <- paste0(
        '{"type":"object","properties":{',
        '"figure_id":{"type":"string"},',
        '"title":{"type":"string"},',
        '"what_is_this":{"type":"string"},',
        '"biological_interpretation":{"type":"string"},',
        '"observations":{"type":"array","items":{"type":"string"}},',
        '"statistical_assessment":{"type":"string"},',
        '"issues_checks":{"type":"array","items":{"type":"string"}},',
        '"next_steps":{"type":"array","items":{"type":"string"}},',
        '"confidence":{"type":"string","enum":["high","medium","low"]}',
        '},"required":["figure_id","what_is_this","biological_interpretation","observations"]}'
    )

    # Build the full prompt with scientific writing principles
    domain_label <- context$domain_label %||% "RNA-seq"
    prompt <- sprintf(
        paste0(
            "You are an expert bioinformatics scientist interpreting %s analysis figures for a report. ",
            "Read the image at '%s' and provide a rigorous scientific interpretation.\n\n",
            "EXPERIMENT CONTEXT:\n%s\n",
            "%s\n\n",
            "WRITING GUIDELINES:\n",
            "- Write 'what_is_this' as a single clear sentence explaining what the figure shows.\n",
            "- Write 'biological_interpretation' as 2-4 sentences of flowing scientific prose — ",
            "this is the main interpretation paragraph that will appear in the report. ",
            "Describe what the data reveals about the biology, name specific patterns you observe, ",
            "and connect observations to the experimental context. ",
            "Do NOT use bullet points in this field.\n",
            "- In 'observations', list 2-4 specific, quantitative observations you can directly see ",
            "(e.g., 'PC1 separates Treatment from Control groups', 'Sample X clusters away from its group').\n",
            "- In 'statistical_assessment', evaluate the statistical quality ",
            "(e.g., adequacy of replication, normalization quality, effect size relative to noise).\n",
            "- In 'issues_checks', flag any quality concerns or potential problems you notice.\n",
            "- In 'next_steps', suggest follow-up analyses if relevant.\n",
            "- Only describe patterns you can directly see in the image. ",
            "Do not invent gene names or numeric values unless clearly visible.\n",
            "- Set figure_id to '%s'."
        ),
        domain_label, image_path, context_str, guidance, figure_id
    )

    model <- config$claude_code_model %||% "sonnet"

    # Allow MCP tools (K-Dense, etc.) if available, plus Read for images
    cmd <- sprintf(
        "unset CLAUDECODE; claude --print --output-format json --model %s --json-schema '%s' --no-session-persistence %s",
        model,
        json_schema,
        shQuote(prompt)
    )

    result <- tryCatch({
        raw <- system(cmd, intern = TRUE, timeout = 180)
        raw_text <- paste(raw, collapse = "\n")

        # Parse the wrapper JSON — structured output is in $structured_output
        parsed <- jsonlite::fromJSON(raw_text, simplifyVector = FALSE)

        # Extract commentary from structured_output (json-schema output)
        commentary <- if (!is.null(parsed$structured_output)) {
            parsed$structured_output
        } else if (!is.null(parsed$result) && nzchar(parsed$result)) {
            tryCatch(
                jsonlite::fromJSON(parsed$result, simplifyVector = FALSE),
                error = function(e) list(what_is_this = parsed$result)
            )
        } else {
            stop("No structured_output or result in Claude Code response")
        }

        commentary$backend <- "claude-code"
        commentary$generated_at <- as.character(Sys.time())

        # Ensure required fields
        if (is.null(commentary$figure_id)) commentary$figure_id <- figure_id
        if (is.null(commentary$observations)) commentary$observations <- list()
        if (is.null(commentary$issues_checks)) commentary$issues_checks <- list()
        if (is.null(commentary$next_steps)) commentary$next_steps <- list()
        # Merge biological_interpretation into what_is_this if needed for backwards compat
        if (is.null(commentary$biological_interpretation)) {
            commentary$biological_interpretation <- ""
        }

        commentary
    }, error = function(e) {
        message("  Claude Code commentary failed: ", e$message)
        create_placeholder_commentary(figure_id,
            reason = paste("Claude Code error:", e$message))
    })

    # Save output
    jsonlite::write_json(result, output_json, auto_unbox = TRUE, pretty = TRUE)

    result
}


# --------------------------------------------------------------------------
# Vision API backend (Claude / OpenAI)
# --------------------------------------------------------------------------

#' Run vision API commentary (Claude or OpenAI)
#'
#' @param image_path  Path to figure image
#' @param figure_id   Figure identifier
#' @param context     Context list
#' @param backend     "claude" or "openai"
#' @param config      Commentary config section
#' @param output_dir  Output directory
#' @return Commentary list
run_vision_commentary <- function(image_path, figure_id, context, backend,
                                   config, output_dir) {

    context_json <- file.path(output_dir, paste0(figure_id, "_context.json"))
    output_json  <- file.path(output_dir, paste0(figure_id, "_commentary.json"))

    # Include guidance in the context passed to the script
    context$figure_guidance <- build_figure_guidance(context)
    jsonlite::write_json(context, context_json, auto_unbox = TRUE, pretty = TRUE)

    # Find script
    script_name <- if (backend == "claude") "figure_commentary_claude.py" else "figure_commentary_openai.py"

    script_candidates <- c(
        file.path(getwd(), "scripts", script_name),
        file.path(config$project_dir %||% ".", "scripts", script_name),
        system.file("scripts", script_name, package = "multiomics.core", mustWork = FALSE)
    )
    script_path <- Find(file.exists, script_candidates)

    if (is.null(script_path)) {
        message("  Commentary script not found: ", script_name)
        return(create_placeholder_commentary(figure_id, reason = "Script not found"))
    }

    # Build model arg
    if (backend == "claude") {
        model <- config$claude_model %||% "claude-sonnet-4-5-20250929"
    } else {
        model <- config$openai_model %||% "gpt-4o"
    }
    max_tokens <- config$max_tokens %||% 1500

    cmd <- sprintf(
        "python3 '%s' --image '%s' --figure_id '%s' --context_json '%s' --out_json '%s' --model '%s' --max_tokens %d",
        script_path, image_path, figure_id, context_json, output_json, model, max_tokens
    )

    max_retries <- config$max_retries %||% 2

    for (attempt in seq_len(max_retries + 1)) {
        result <- tryCatch({
            system(cmd, intern = TRUE, ignore.stderr = FALSE, timeout = 120)
            if (file.exists(output_json)) {
                commentary <- jsonlite::read_json(output_json)
                commentary$backend <- backend
                commentary$generated_at <- as.character(Sys.time())
                return(commentary)
            } else {
                stop("Output JSON not created")
            }
        }, error = function(e) {
            if (attempt <= max_retries) {
                message("  Attempt ", attempt, " failed: ", e$message, ". Retrying...")
                Sys.sleep(3)
                return(NULL)
            } else {
                message("  API call failed after ", max_retries + 1, " attempts: ", e$message)
                return(create_placeholder_commentary(figure_id,
                    reason = paste("API error:", e$message)))
            }
        })

        if (!is.null(result) && is.list(result)) return(result)
    }

    create_placeholder_commentary(figure_id, reason = "API call failed")
}


# --------------------------------------------------------------------------
# Placeholder
# --------------------------------------------------------------------------

#' Create placeholder commentary
#' @param figure_id Figure identifier
#' @param reason Reason text
#' @return Commentary list
create_placeholder_commentary <- function(figure_id, reason = "Commentary disabled") {
    list(
        figure_id    = figure_id,
        title        = "Commentary Unavailable",
        what_is_this = paste("Automated commentary is not available.", reason),
        biological_interpretation = "",
        observations = list("Please refer to the figure and its caption for interpretation."),
        statistical_assessment = "",
        issues_checks = list(),
        next_steps    = list(),
        confidence    = "none",
        backend       = "placeholder",
        generated_at  = as.character(Sys.time())
    )
}


# --------------------------------------------------------------------------
# Data-driven fallback (no LLM) — enriched with actual data
# --------------------------------------------------------------------------

#' Generate data-driven fallback commentary (no LLM)
#' @param fig Figure row
#' @param context Context list (enriched)
#' @param de_summary DE summary data frame
#' @return Commentary list
generate_fallback_commentary <- function(fig, context, de_summary = NULL) {
    commentary <- list(
        figure_id    = fig$figure_id,
        title        = fig$title,
        backend      = "data_driven",
        generated_at = as.character(Sys.time()),
        confidence   = "medium",
        statistical_assessment = ""
    )

    pt <- fig$plot_type
    fid <- fig$figure_id
    organism <- context$organism %||% "the organism under study"
    groups <- context$groups
    group_str <- if (!is.null(groups)) paste(groups, collapse = ", ") else "the experimental groups"

    # --- PCA ---
    if (pt == "scatter" && grepl("pca", fid, ignore.case = TRUE)) {
        var_str <- ""
        if (!is.null(context$pca_var_pc1)) {
            if (grepl("PC3|13", fid) && !is.null(context$pca_var_pc3)) {
                var_str <- sprintf(
                    " PC1 captures %.1f%% of the total variance and PC3 captures %.1f%%.",
                    context$pca_var_pc1, context$pca_var_pc3
                )
            } else {
                var_str <- sprintf(
                    " PC1 captures %.1f%% of the total variance and PC2 captures %.1f%%, together explaining %.1f%% of the overall variation.",
                    context$pca_var_pc1, context$pca_var_pc2,
                    context$pca_var_pc1 + context$pca_var_pc2
                )
            }
        }
        commentary$what_is_this <- "Principal Component Analysis (PCA) of all samples based on normalized gene expression values. Each point represents a sample, colored by experimental group."
        commentary$biological_interpretation <- paste0(
            "PCA reduces the high-dimensional expression data to its main axes of variation, allowing assessment of sample relationships.",
            var_str,
            " Samples from the same experimental group (", group_str, ") are expected to cluster together if the treatment effect is the dominant source of variation.",
            " Separation along PC1 typically reflects the strongest biological or technical effect in the dataset."
        )
        commentary$observations <- list(
            "Samples are colored by experimental condition and projected onto principal component axes",
            paste0("Groups in this experiment: ", group_str),
            "Look for clear separation between conditions and tight within-group clustering"
        )
        commentary$statistical_assessment <- paste0(
            "PCA is an unsupervised method — no statistical test is performed. ",
            "The proportion of variance explained by each PC indicates how much of the total variation is captured.",
            if (!is.null(context$pca_var_pc1) && context$pca_var_pc1 > 40)
                " A dominant PC1 (>40% variance) suggests a strong effect driving the transcriptome."
            else ""
        )
        commentary$issues_checks <- list(
            "Check if samples cluster by condition rather than by batch or other technical factors",
            "Any sample falling far from its group centroid may be an outlier worth investigating"
        )
        commentary$next_steps <- list("Investigate any outlier samples for potential quality issues before DE analysis")

    # --- Raw boxplot ---
    } else if (pt == "boxplot" && grepl("raw", fid)) {
        commentary$what_is_this <- "Per-sample boxplots of raw (un-normalized) log2-transformed expression values."
        commentary$biological_interpretation <- paste0(
            "This plot shows the expression distribution for each sample before normalization. ",
            "Differences in box height and median position reflect library-size variation and other technical factors. ",
            "These differences should be corrected by normalization in subsequent steps."
        )
        commentary$observations <- list(
            "Each box represents one sample's expression distribution",
            "Variation in median and spread is expected before normalization"
        )
        commentary$issues_checks <- list(
            "Samples with dramatically different distributions may have quality issues"
        )
        commentary$next_steps <- list()

    # --- Normalized boxplot ---
    } else if (pt == "boxplot") {
        norm_str <- if (!is.null(context$norm_method)) context$norm_method else "TMM + log2 CPM"
        commentary$what_is_this <- sprintf("Per-sample boxplots of normalized expression values (%s).", norm_str)
        commentary$biological_interpretation <- paste0(
            "After normalization (", norm_str, "), all samples should show comparable expression distributions. ",
            "Similar medians and interquartile ranges across samples confirm that technical variation has been adequately removed, ",
            "leaving biological differences as the primary source of variation for downstream analysis."
        )
        commentary$observations <- list(
            "Medians should be aligned across samples after normalization",
            "Interquartile ranges should be similar across samples"
        )
        commentary$issues_checks <- list(
            "Samples with notably different distributions after normalization may need investigation"
        )
        commentary$next_steps <- list()

    # --- Density ---
    } else if (pt == "density") {
        commentary$what_is_this <- "Per-sample expression density curves showing the distribution of normalized gene expression values."
        commentary$biological_interpretation <- paste0(
            "The density curves visualize the overall shape of each sample's expression distribution after normalization. ",
            "Overlapping curves indicate consistent normalization. ",
            "RNA-seq data typically shows a bimodal pattern: a peak at low/zero expression (non-expressed genes) ",
            "and a broader peak at higher expression levels."
        )
        commentary$observations <- list(
            "Each curve represents one sample's expression distribution",
            "Curves should largely overlap after normalization"
        )
        commentary$issues_checks <- list(
            "Samples with shifted or differently shaped curves may indicate quality issues"
        )
        commentary$next_steps <- list()

    # --- Correlation heatmap ---
    } else if (pt == "heatmap" && grepl("correlation", fid)) {
        commentary$what_is_this <- "Pearson correlation heatmap between all sample pairs based on genome-wide normalized expression profiles."
        commentary$biological_interpretation <- paste0(
            "High Pearson correlation (>0.95) between biological replicates indicates consistent expression profiles. ",
            "Block-diagonal structure — with high within-group and lower between-group correlation — ",
            "confirms that the experimental conditions (", group_str, ") are the main driver of expression differences."
        )
        commentary$observations <- list(
            "Biological replicates should show high correlation (>0.9, typically >0.95)",
            "Between-group correlation may be lower, reflecting biological differences"
        )
        commentary$issues_checks <- list(
            "Samples with notably low correlation to all others (including their own group) may be outliers"
        )
        commentary$next_steps <- list()

    # --- Distance heatmap ---
    } else if (pt == "heatmap" && grepl("distance", fid)) {
        commentary$what_is_this <- "Euclidean distance heatmap between all sample pairs, reflecting overall expression dissimilarity."
        commentary$biological_interpretation <- paste0(
            "Sample distance matrices complement correlation analysis by capturing absolute expression differences. ",
            "Replicates within the same condition (", group_str, ") should have low distances (dark colors), ",
            "while samples from different conditions should show larger distances."
        )
        commentary$observations <- list(
            "Low distance (dark) between replicates indicates good reproducibility",
            "Hierarchical clustering dendrograms should group replicates by condition"
        )
        commentary$issues_checks <- list(
            "If samples cluster by batch rather than condition, batch correction may be needed"
        )
        commentary$next_steps <- list()

    # --- Expression heatmap ---
    } else if (pt == "heatmap" && grepl("expr_heatmap", fid)) {
        commentary$what_is_this <- "Heatmap of z-score-scaled expression values for top variable genes across all samples, with hierarchical clustering."
        commentary$biological_interpretation <- paste0(
            "This heatmap provides a global view of expression patterns across the most variable genes. ",
            "Row clustering reveals co-expressed gene modules, while column clustering should ideally group ",
            "samples by experimental condition (", group_str, "). ",
            "Blocks of up- or down-regulated genes in specific conditions highlight the major transcriptomic signatures."
        )
        commentary$observations <- list(
            "Gene expression values are row-scaled (z-scores) for visualization",
            "Column dendrogram should cluster samples by experimental condition"
        )
        commentary$issues_checks <- list(
            "If samples cluster by batch rather than condition, consider batch correction"
        )
        commentary$next_steps <- list("Examine gene clusters for functional enrichment")

    # --- Volcano ---
    } else if (pt == "volcano") {
        gene_obs <- list()
        if (!is.null(context$top_genes)) {
            tg <- context$top_genes
            top_up <- tg[tg$direction == "up", ]
            top_dn <- tg[tg$direction == "down", ]
            if (nrow(top_up) > 0) {
                gene_obs <- c(gene_obs, sprintf(
                    "Top up-regulated: %s",
                    paste(sprintf("%s (log2FC=%.1f)", top_up$gene, top_up$log2FC), collapse = ", ")
                ))
            }
            if (nrow(top_dn) > 0) {
                gene_obs <- c(gene_obs, sprintf(
                    "Top down-regulated: %s",
                    paste(sprintf("%s (log2FC=%.1f)", top_dn$gene, top_dn$log2FC), collapse = ", ")
                ))
            }
        }

        de_str <- ""
        if (!is.null(context$de_significant)) {
            de_str <- sprintf(
                " In the %s comparison, %s genes were identified as significantly differentially expressed (%s up-regulated, %s down-regulated).",
                gsub("_", " vs ", context$contrast %||% ""),
                context$de_significant,
                context$de_up %||% "?",
                context$de_down %||% "?"
            )
        }

        commentary$what_is_this <- "Volcano plot showing statistical significance versus effect size for all tested genes."
        commentary$biological_interpretation <- paste0(
            "Each point represents a gene, with log2 fold change on the x-axis and -log10 adjusted p-value on the y-axis. ",
            "Colored points exceed both the fold-change and significance cutoffs (dashed lines).",
            de_str
        )

        obs <- list()
        if (!is.null(context$de_significant)) {
            obs <- c(obs, sprintf("Total significant genes: %s (%s up, %s down)",
                                   context$de_significant, context$de_up %||% "?", context$de_down %||% "?"))
        }
        obs <- c(obs, gene_obs)
        if (length(obs) == 0) obs <- list("See the DE summary table for detailed counts")
        commentary$observations <- obs
        commentary$issues_checks <- list()
        commentary$next_steps <- list()

    # --- MA ---
    } else if (pt == "ma_plot") {
        commentary$what_is_this <- "MA plot (mean-difference plot) showing fold change versus average expression for all genes."
        commentary$biological_interpretation <- paste0(
            "The MA plot displays log2 fold change against mean expression for each gene. ",
            "After proper normalization, the cloud of non-significant genes should be centered symmetrically around log2FC = 0. ",
            "Higher variance at low expression levels is an inherent property of count data. ",
            "Significant genes (colored) at higher expression levels represent the most reliable DE calls."
        )
        commentary$observations <- list(
            "The main cloud should be centered at log2FC = 0 across all expression levels",
            "Lowly expressed genes (left side) have higher fold-change variance, which is expected"
        )
        commentary$issues_checks <- list(
            "Asymmetry or trends in the cloud may suggest normalization issues"
        )
        commentary$next_steps <- list()

    # --- Top DE heatmap ---
    } else if (pt == "heatmap" && grepl("heatmap_top", fid)) {
        commentary$what_is_this <- "Heatmap of z-score-scaled expression for the top differentially expressed genes in this contrast."
        commentary$biological_interpretation <- paste0(
            "This heatmap focuses on genes that passed the significance and fold-change cutoffs, ",
            "showing their expression patterns across all samples. ",
            "Clear separation between the conditions confirms that the DE genes capture real biological differences."
        )
        commentary$observations <- list(
            "Samples should cluster by experimental condition",
            "Gene clusters with coordinated expression may represent co-regulated pathways"
        )
        commentary$issues_checks <- list(
            "If samples do not separate cleanly, some DE calls may be driven by outlier samples"
        )
        commentary$next_steps <- list("Examine gene clusters for functional enrichment")

    # --- Pathway dotplot ---
    } else if (pt == "dotplot") {
        commentary$what_is_this <- "Pathway enrichment dot plot showing statistically enriched biological pathways or gene sets."
        commentary$biological_interpretation <- paste0(
            "Enrichment analysis identifies biological pathways that are over-represented among the differentially expressed genes. ",
            "Dot size indicates the number of overlapping genes, while color reflects statistical significance. ",
            "Top pathways reveal the biological processes most affected by the experimental condition in ", organism, "."
        )
        commentary$observations <- list(
            "Pathways are ranked by enrichment score or significance",
            "Larger dots indicate more genes from the pathway are differentially expressed"
        )
        commentary$issues_checks <- list()
        commentary$next_steps <- list("Focus on pathways relevant to your biological question for validation")

    # --- Generic ---
    } else {
        commentary$what_is_this <- fig$description
        commentary$biological_interpretation <- "See the figure for details."
        commentary$observations <- list("Please refer to the figure and its caption for interpretation.")
        commentary$issues_checks <- list()
        commentary$next_steps <- list()
        commentary$confidence <- "low"
    }

    commentary
}


# --------------------------------------------------------------------------
# Utilities
# --------------------------------------------------------------------------

#' Get commentary for a specific figure from the combined list
#' @param commentary_list Named list from generate_all_commentary()
#' @param figure_id Figure identifier
#' @return Commentary list or NULL
get_figure_commentary <- function(commentary_list, figure_id) {
    if (is.null(commentary_list)) return(NULL)
    commentary_list[[figure_id]]
}


#' Format commentary as HTML for embedding in Rmd reports
#' @param commentary Commentary list for a single figure
#' @return HTML string
format_commentary_html <- function(commentary) {
    if (is.null(commentary)) return("")

    html <- "<div class='commentary-block' style='background: #f8f9fa; border-left: 4px solid #4a90d9; padding: 12px 16px; margin: 10px 0 20px 0; border-radius: 0 4px 4px 0; font-size: 0.92em;'>\n"

    # What is this figure
    html <- paste0(html, "<p style='margin: 0 0 8px 0;'><strong>What this shows:</strong> ",
                   htmltools::htmlEscape(commentary$what_is_this %||% ""), "</p>\n")

    # Biological interpretation (new field — the main prose paragraph)
    bio_interp <- commentary$biological_interpretation %||% ""
    if (nzchar(bio_interp)) {
        html <- paste0(html, "<p style='margin: 4px 0 8px 0;'><strong>Interpretation:</strong> ",
                       htmltools::htmlEscape(bio_interp), "</p>\n")
    }

    # Observations
    obs <- commentary$observations
    if (length(obs) > 0 && obs[[1]] != "") {
        html <- paste0(html, "<p style='margin: 4px 0;'><strong>Key observations:</strong></p>\n<ul style='margin: 2px 0 8px 0; padding-left: 20px;'>\n")
        for (o in obs) {
            html <- paste0(html, "<li>", htmltools::htmlEscape(o), "</li>\n")
        }
        html <- paste0(html, "</ul>\n")
    }

    # Statistical assessment (new field)
    stat_assess <- commentary$statistical_assessment %||% ""
    if (nzchar(stat_assess)) {
        html <- paste0(html, "<p style='margin: 4px 0 8px 0;'><strong>Statistical note:</strong> ",
                       htmltools::htmlEscape(stat_assess), "</p>\n")
    }

    # Issues / checks
    issues <- commentary$issues_checks
    if (length(issues) > 0 && issues[[1]] != "") {
        html <- paste0(html, "<p style='margin: 4px 0;'><strong>Checks:</strong></p>\n<ul style='margin: 2px 0 8px 0; padding-left: 20px;'>\n")
        for (issue in issues) {
            html <- paste0(html, "<li>", htmltools::htmlEscape(issue), "</li>\n")
        }
        html <- paste0(html, "</ul>\n")
    }

    # Next steps
    steps <- commentary$next_steps
    if (length(steps) > 0 && steps[[1]] != "") {
        html <- paste0(html, "<p style='margin: 4px 0;'><strong>Next steps:</strong></p>\n<ul style='margin: 2px 0 4px 0; padding-left: 20px;'>\n")
        for (s in steps) {
            html <- paste0(html, "<li>", htmltools::htmlEscape(s), "</li>\n")
        }
        html <- paste0(html, "</ul>\n")
    }

    # Footer with attribution
    backend <- commentary$backend %||% "unknown"
    confidence <- commentary$confidence %||% ""
    backend_label <- if (grepl("claude", backend, ignore.case = TRUE)) {
        "Claude (Anthropic) + K-Dense AI scientific-skills"
    } else if (grepl("openai", backend, ignore.case = TRUE)) {
        "OpenAI + K-Dense AI scientific-skills"
    } else if (backend == "data_driven") {
        "data-driven + K-Dense AI scientific-skills"
    } else {
        backend
    }
    if (nzchar(confidence) && confidence != "none") {
        backend_label <- paste0(backend_label, " | confidence: ", confidence)
    }
    html <- paste0(html, "<p style='margin: 4px 0 0 0; color: #888; font-size: 0.85em;'>",
                   "<em>Generated by: ", htmltools::htmlEscape(backend_label), "</em></p>\n")

    html <- paste0(html, "</div>\n")
    html
}
