# R/domain/metabolomics/06g_mummichog_gsea.R
#
# GSEA for untargeted MS peaks-to-pathways, run in EmpiricalCompound space —
# MetaboAnalyst's complementary analysis to mummichog's over-representation test
# (ORA). It is ADDITIVE: the pinned mummichog 2.7.0 ORA (06c/05b) and everything
# derived from it are left exactly as they are, including the ORA input contract
# (which sends logFC as mummichog's `statistic` column) and the ORA p-values,
# overlaps and evidence.
#
# The two analyses answer different questions:
#
#   * ORA  — takes only the features/ECs passing the significance cutoff, asks
#            whether they over-populate a pathway, and reports the overlap, the
#            detected pathway size and an empirical permutation p-value.
#   * GSEA — takes the COMPLETE ranked EC list with no significance cutoff and
#            asks whether a pathway's ECs sit systematically at one end of that
#            ranking (ES / NES / p / BH-adjusted p).
#
# ===========================================================================
# BEHAVIOURAL REFERENCE — pinned upstream version
# ===========================================================================
# Everything below reproduces MetaboAnalystR at
#
#     repo:   xia-lab/MetaboAnalystR
#     commit: 398476ae2a0c996e390925fa62adc46b5ecde334
#     files:  R/peaks_to_function.R, R/util_fgsea.R
#
# (Both files are byte-identical between that commit and upstream's current
# default-branch head, so the pin is the live Peaks-to-Pathways code path, not a
# stale one.)
#
# Upstream call chain for our configuration (retention time present, version
# "v2" — see PerformPSEA() -> .init.RT.Permutations()):
#
#     PerformPSEA(..., permNum = 100)          # peaks_to_function.R:1126
#       -> .init.RT.Permutations()             # peaks_to_function.R:1310
#         -> .compute.mummichog.RT.fgsea()     # peaks_to_function.R:3457
#           -> fgsea2()                        # peaks_to_function.R:4643
#             -> my.fgsea()                    # util_fgsea.R:1
#               -> .run_fgsea_inner()          # util_fgsea.R:41
#
# `.run_fgsea_inner()` is a vendored variant of fgsea's fixed-permutation
# scheme, and it is NOT reachable through any public fgsea entry point:
#
#   * it is handed TWO vectors — `stats` (one entry per UNIQUE score, named by
#     the ";"-joined ids sharing it) and `ranks` (one entry per EC, valued with
#     that EC's tie-group index) — whereas fgseaSimple() takes a single named
#     per-item vector and resolves positions itself;
#   * pathway members become tie-group INDICES (`ranks[pos]`) and are NOT
#     de-duplicated, so two ECs in one tie group are counted twice in the set
#     size and in the enrichment score; fgseaSimple() applies `unique()`;
#   * it applies `abs()` BEFORE sorting (`stats <- abs(stats)^gseaParam`, then
#     `stats <- sort(stats, decreasing = TRUE)` on fgsea > 1.24.0), whereas
#     fgseaSimple() sorts the SIGNED values first and takes `abs()` afterwards —
#     a different ranking whenever any score is negative.
#
# So `fgseaSimple()` cannot reproduce it, and mmc_gsea_metaboanalyst() below is
# the smallest local helper that does. It is not a second GSEA engine: the
# enrichment score and the permutation batch still come from fgsea's own
# primitives (`fgsea::calcGseaStat`, `fgsea:::calcGseaStatCumulativeBatch`),
# exactly as upstream calls them, and the ES/NES/p/BH arithmetic is upstream's
# line for line. A parity fixture generated by running the pinned
# `.run_fgsea_inner()` itself locks this down (see
# tests/testthat/fixtures/mummichog_gsea_parity/).
#
# Consequence for interpretation: pathway positions are built from the SIGNED
# ordering and are then scored against a vector that has been made absolute AND
# re-sorted, so a pathway's indices need not correspond to where its ECs sit in
# the ranking that is actually scored. ES/NES sign is therefore kept only for
# parity and must not be read as a direction of any kind — not biological
# up/down, and not a statement about the members' score magnitudes. See
# mmc_gsea_nes_note().
#
# Other semantics carried over from the pinned source:
#
#  1. RANKING STATISTIC — `PreparePeakTable4PSEA()` ranks on the t-score: the
#     limma moderated `t` when the limma path is taken, otherwise the t-test /
#     ANOVA statistic. Not the fold change. Our per-contrast limma tables carry
#     that moderated `t` in their `statistic` column (see `de_limma()`), so that
#     is the preferred metric here; `logFC` is used only when a DE table has no
#     usable statistic. The choice is recorded in the result and the report.
#
#  2. EC SCORE — `peaks_to_function.R`, the `mumRT && version=="v2"` branch:
#     features sharing one m/z are merged by `rank.metric` (default "mean"),
#     then `ec.exp.vec <- unlist(lapply(ec_exp_dict, max))` — an EC's score is
#     the SIGNED maximum of its member features' scores. Not the mean, not
#     `max(abs())`, not the most significant feature. See mmc_ec_scores().
#
#  3. GENE SETS — `current.mset <- mSetObj$pathways$emp_cpds`: pathway ->
#     detected EmpiricalCompounds. See mmc_pathway_ec_sets().
#
#  4. DEFAULTS — `permNum = 100` (PerformPSEA), `gseaParam = 1`, `minSize = 1`,
#     `maxSize = Inf`, `set.seed(123)` (.run_fgsea_inner).
#
#  5. MULTIPLE TESTING — `p.adjust(pval, method = "fdr")` over exactly the
#     pathways kept by the size filter, i.e. the tested universe.
#
# Dependencies (R): fgsea (already used by run_metabolomics_gsea), fastmatch,
# data.table, BiocParallel, ggplot2, optionally ggrepel. All in renv.lock.


# The pinned upstream reference, surfaced for provenance in results and reports.
.MMC_GSEA_REF_COMMIT <- "398476ae2a0c996e390925fa62adc46b5ecde334"
.MMC_GSEA_REF_REPO   <- "xia-lab/MetaboAnalystR"

# MetaboAnalyst-equivalent defaults. Changing any of these is a methodological
# deviation and is recorded as such in the result (see run_mummichog_gsea()).
.MMC_GSEA_DEFAULTS <- list(
  n_perm     = 100L,      # PerformPSEA(permNum = 100)
  gsea_param = 1,         # .run_fgsea_inner(gseaParam = 1)
  min_size   = 1,         # .run_fgsea_inner(minSize = 1)
  max_size   = Inf,       # .run_fgsea_inner(maxSize = Inf)
  seed       = 123L       # .run_fgsea_inner: set.seed(123)
)

# Upstream's permutation batch size (util_fgsea.R: `granularity <- 1000`).
.MMC_GSEA_GRANULARITY <- 1000


# ==== ranking statistic =====================================================

#' Choose and extract the signed GSEA ranking statistic from a DE table
#'
#' Prefers the moderated `t` statistic (our limma tables expose it as
#' `statistic`; a literal `t` column is also accepted) because that is what
#' MetaboAnalyst's peaks-to-pathways GSEA ranks on, and falls back to `logFC`
#' when no usable statistic is present. The ORA input contract is untouched —
#' this function is only ever used for GSEA.
#'
#' @param de_table One contrast's DE table (needs `feature_id` and at least one
#'   of `statistic` / `t` / `logFC`).
#' @return A list with `values` (named numeric vector, keyed by `feature_id`,
#'   finite values only), `metric` (`"moderated_t"` or `"logFC"`) and `label`
#'   (a human-readable provenance string). `NULL` when nothing is usable.
mmc_gsea_rank_metric <- function(de_table) {
  if (is.null(de_table) || !is.data.frame(de_table) || nrow(de_table) == 0 ||
      !"feature_id" %in% names(de_table)) {
    return(NULL)
  }
  stat_col <- .mmc_find_col(de_table, c("statistic", "t"))
  usable <- function(col) {
    if (is.null(col) || !col %in% names(de_table)) return(FALSE)
    v <- suppressWarnings(as.numeric(de_table[[col]]))
    any(is.finite(v))
  }

  if (usable(stat_col)) {
    v      <- suppressWarnings(as.numeric(de_table[[stat_col]]))
    metric <- "moderated_t"
    label  <- paste0("moderated t statistic (DE column '", stat_col, "')")
  } else if (usable("logFC")) {
    v      <- suppressWarnings(as.numeric(de_table$logFC))
    metric <- "logFC"
    label  <- "log2 fold change (no t statistic in the DE table)"
  } else {
    return(NULL)
  }

  keep <- is.finite(v)
  if (!any(keep)) return(NULL)
  list(
    values = stats::setNames(v[keep], as.character(de_table$feature_id)[keep]),
    metric = metric,
    label  = label
  )
}


# ==== EmpiricalCompound scores ==============================================

#' Build the EmpiricalCompound score vector (MetaboAnalyst v2 semantics)
#'
#' Two steps, reproducing MetaboAnalystR's EC-space construction exactly:
#'
#' \enumerate{
#'   \item features that share the same m/z are merged with `rank_metric`
#'     (MetaboAnalyst's default is `"mean"`), then
#'   \item each EmpiricalCompound takes the **signed maximum** of its member
#'     features' merged scores.
#' }
#'
#' The signed max is MetaboAnalyst's rule (`unlist(lapply(ec_exp_dict, max))`),
#' not an aggregation we chose: no mean, no `max(abs())`, no "most significant
#' feature", and no direction invented at the EC level.
#'
#' @param ec_features  Per-(EC, feature) frame from `read_mummichog_ec_features()`
#'   (needs `EID`, `feature_id`, `mz`).
#' @param feature_scores Named numeric vector of per-feature ranking statistics,
#'   keyed by `feature_id` (from `mmc_gsea_rank_metric()$values`).
#' @param rank_metric  How to merge features sharing one m/z: `"mean"` (default,
#'   MetaboAnalyst's default), `"min"`, `"max"` or `"median"`.
#' @return A named numeric vector of EC scores, sorted decreasing; empty named
#'   numeric when nothing can be scored.
mmc_ec_scores <- function(ec_features, feature_scores,
                          rank_metric = c("mean", "min", "max", "median")) {
  rank_metric <- match.arg(rank_metric)
  out <- stats::setNames(numeric(0), character(0))
  if (is.null(ec_features) || !is.data.frame(ec_features) ||
      nrow(ec_features) == 0 || length(feature_scores) == 0) {
    return(out)
  }
  score <- unname(feature_scores[as.character(ec_features$feature_id)])
  # Keyed on the m/z string mummichog echoed back, so the grouping matches its
  # own notion of "the same m/z" without float-equality surprises. A missing m/z
  # becomes its own group rather than being dropped by the formula interface.
  mz <- as.character(ec_features$mz)
  na_mz <- is.na(mz)
  if (any(na_mz)) mz[na_mz] <- paste0("<na>", which(na_mz))

  df <- data.frame(
    EID   = as.character(ec_features$EID),
    mz    = mz,
    score = score,
    stringsAsFactors = FALSE
  )
  df <- df[is.finite(df$score) & !is.na(df$EID), , drop = FALSE]
  if (nrow(df) == 0) return(out)

  # -- step 1: merge scores of features sharing one m/z ----------------------
  agg <- switch(rank_metric,
                mean   = mean,
                min    = min,
                max    = max,
                median = stats::median)
  merged <- stats::aggregate(score ~ mz, data = df, FUN = agg)
  df$score <- merged$score[match(df$mz, merged$mz)]

  # -- step 2: EC score = signed max over its member features ---------------
  # Distinct (EC, m/z) pairs only: an m/z matching the same EC through several
  # candidate compounds must not weight the max differently.
  uniq <- unique(df[, c("EID", "mz", "score")])
  ec   <- stats::aggregate(score ~ EID, data = uniq, FUN = max)
  sort(stats::setNames(ec$score, ec$EID), decreasing = TRUE)
}

#' Build pathway gene-set equivalents: pathway -> detected EmpiricalCompounds
#'
#' An EmpiricalCompound belongs to a pathway when ANY of its candidate compounds
#' is a compound of that pathway — the same relation MetaboAnalyst holds as
#' `mSetObj$pathways$emp_cpds`. Only ECs present in `ec_ids` (the ranked
#' universe) are kept, so set sizes describe what was actually detected.
#'
#' @param model_pathways Named list: pathway -> compound ids (from
#'   `read_mummichog_model_pathways()$pathways`).
#' @param ec_candidates  Long EC -> candidate frame from
#'   `read_mummichog_ec_candidates()`.
#' @param ec_ids         Character vector of ECs in the ranked universe.
#' @return Named list: pathway -> character vector of detected EC ids. Pathways
#'   with no detected EC are dropped.
mmc_pathway_ec_sets <- function(model_pathways, ec_candidates, ec_ids) {
  if (length(model_pathways) == 0 || is.null(ec_candidates) ||
      nrow(ec_candidates) == 0 || length(ec_ids) == 0) {
    return(list())
  }
  cand <- ec_candidates[ec_candidates$EID %in% ec_ids, , drop = FALSE]
  if (nrow(cand) == 0) return(list())
  # compound id -> ECs that carry it as a candidate
  cpd_to_ec <- split(cand$EID, cand$compound_id)

  sets <- lapply(model_pathways, function(cpds) {
    hits <- cpd_to_ec[intersect(cpds, names(cpd_to_ec))]
    unique(unlist(hits, use.names = FALSE))
  })
  sets[vapply(sets, length, integer(1)) > 0L]
}


# ==== upstream ranked-input construction ====================================

#' Build the two ranked vectors MetaboAnalyst's GSEA engine consumes
#'
#' Reproduces the construction in the pinned
#' `peaks_to_function.R::.compute.mummichog.RT.fgsea()` (lines 3470-3483)
#' verbatim in behaviour:
#'
#' \preformatted{
#' df.scores  <- data.frame(id = names(total_ecpds), scores = total_ecpds)
#' ag.scores  <- aggregate(id ~ scores, data = df.scores, paste, collapse = "; ")
#' ag.sorted  <- ag.scores[order(-ag.scores$scores), ]
#' dt.scores.out <- <one row per EC, carrying its tie-group row index>
#' rank.vec   <- tie-group index, named by EC id
#' scores.vec <- unique signed scores, named by the ";"-joined EC ids
#' }
#'
#' So ECs that share a score are COLLAPSED into one ranked position whose name
#' is the `"; "`-joined list of their ids, and `ranks` maps every individual EC
#' to that position's index. Both vectors are ordered by descending SIGNED
#' score. This is what makes the engine's index semantics non-trivial, and it is
#' why the ranked vector is shorter than the EC universe whenever scores tie.
#'
#' @param ec_scores Named numeric vector of signed EC scores (from
#'   `mmc_ec_scores()`).
#' @return A list with `stats` (unique signed scores, descending, named by the
#'   `"; "`-joined EC ids) and `ranks` (per-EC tie-group index, named by EC id).
#'   Both empty when `ec_scores` is empty.
mmc_gsea_ranked_inputs <- function(ec_scores) {
  empty <- list(stats = stats::setNames(numeric(0), character(0)),
                ranks = stats::setNames(numeric(0), character(0)))
  if (length(ec_scores) == 0 || is.null(names(ec_scores))) return(empty)
  keep <- is.finite(ec_scores) & nzchar(names(ec_scores))
  ec_scores <- ec_scores[keep]
  if (length(ec_scores) == 0) return(empty)

  df <- data.frame(id = names(ec_scores), scores = unname(ec_scores),
                   stringsAsFactors = FALSE)
  ag <- stats::aggregate(id ~ scores, data = df, paste, collapse = "; ")
  ag <- ag[order(-ag$scores), , drop = FALSE]
  rownames(ag) <- NULL

  stats_vec <- stats::setNames(as.numeric(ag$scores), as.character(ag$id))

  # Expand each tie group back to its member ECs, carrying the group's index —
  # upstream's data.table `by = 1:nrow(dt.scores)` idiom.
  idx  <- lapply(seq_len(nrow(ag)),
                 function(i) strsplit(as.character(ag$id[i]), "; ",
                                      fixed = TRUE)[[1]])
  ranks_vec <- stats::setNames(
    as.numeric(rep(seq_len(nrow(ag)), vapply(idx, length, integer(1)))),
    unlist(idx, use.names = FALSE)
  )
  list(stats = stats_vec, ranks = ranks_vec)
}


# ==== MetaboAnalyst-equivalent GSEA engine ==================================

#' Run MetaboAnalystR's vendored fixed-permutation GSEA
#'
#' A line-for-line reproduction of the pinned
#' `util_fgsea.R::.run_fgsea_inner()` (see the file header for why no public
#' fgsea entry point can stand in for it). The enrichment score and the
#' permutation batch come from fgsea's own primitives, called exactly as
#' upstream calls them:
#'
#' \itemize{
#'   \item `stats <- abs(stats)^gseaParam`, then — on fgsea > 1.24.0, which is
#'     the branch upstream takes for any modern fgsea —
#'     `stats <- sort(stats, decreasing = TRUE)`. `abs()` BEFORE the sort is
#'     what makes the ranking a |score| ranking, and the re-sort happens AFTER
#'     the pathway positions were derived from the signed ordering, which is why
#'     ES/NES sign carries no interpretable direction (see
#'     `mmc_gsea_nes_note()`).
#'   \item pathway members become tie-group indices via
#'     `ranks[na.omit(fmatch(members, names(ranks)))]`, NOT de-duplicated, so
#'     two ECs in one tie group count twice toward `size` and the ES.
#'   \item `fgsea::calcGseaStat(..., returnLeadingEdge = TRUE)` for ES.
#'   \item `fgsea:::calcGseaStatCumulativeBatch(..., seed = seeds[i],
#'     scoreType = "std")` for the permutation tallies (the `m == 1` case uses
#'     upstream's plain `sample.int()` loop instead).
#'   \item `pval = min((1+leEs)/(1+leZero), (1+geEs)/(1+geZero))`,
#'     `NES = ES / mean(same-sign permuted ES)`,
#'     `padj = p.adjust(pval, "fdr")` over the kept pathways only.
#'   \item leading edge = `names(stats)[le]` split on `"; "`, intersected with
#'     the pathway's own EC ids.
#' }
#'
#' @param pathways Named list: pathway -> character vector of EC ids.
#' @param stats    Ranked score vector from `mmc_gsea_ranked_inputs()$stats`.
#' @param ranks    Per-EC tie-group index from `mmc_gsea_ranked_inputs()$ranks`.
#' @param n_perm   Permutations (upstream default 100).
#' @param min_size,max_size Size bounds on the tie-group index vector
#'   (upstream defaults 1 and `Inf`).
#' @param gsea_param Enrichment-score weight exponent (upstream default 1).
#' @param seed     Seed for the permutation batch seeds (upstream `set.seed(123)`).
#' @return A data.frame with one row per TESTED pathway: `pathway`, `pval`,
#'   `padj`, `ES`, `NES`, `nMoreExtreme`, `size`, `leadingEdge` (`"; "`-joined
#'   EC ids), `es_defaulted` (TRUE when upstream's tryCatch fallback supplied
#'   `ES = 0` instead of a computed score) and `es_reason` (why, from
#'   `.mmc_gsea_fallback_reason()`; `NA` when the score was computed). Zero rows
#'   when no pathway passes the size filter.
mmc_gsea_metaboanalyst <- function(pathways, stats, ranks,
                                   n_perm     = .MMC_GSEA_DEFAULTS$n_perm,
                                   min_size   = .MMC_GSEA_DEFAULTS$min_size,
                                   max_size   = .MMC_GSEA_DEFAULTS$max_size,
                                   gsea_param = .MMC_GSEA_DEFAULTS$gsea_param,
                                   seed       = .MMC_GSEA_DEFAULTS$seed) {
  empty <- data.frame(pathway = character(0), pval = numeric(0),
                      padj = numeric(0), ES = numeric(0), NES = numeric(0),
                      nMoreExtreme = numeric(0), size = numeric(0),
                      leadingEdge = character(0), stringsAsFactors = FALSE)
  if (length(pathways) == 0 || length(stats) == 0 || length(ranks) == 0) {
    return(empty)
  }
  for (pkg in c("fgsea", "fastmatch", "data.table", "BiocParallel")) {
    if (!requireNamespace(pkg, quietly = TRUE)) {
      .mmc_stop("package '", pkg, "' is required for the MetaboAnalyst-style ",
                "GSEA engine.")
    }
  }

  # -- permutation batching + batch seeds (upstream, verbatim) ---------------
  granularity <- .MMC_GSEA_GRANULARITY
  perm_per_proc <- rep(granularity, floor(n_perm / granularity))
  if (n_perm - sum(perm_per_proc) > 0) {
    perm_per_proc <- c(perm_per_proc, n_perm - sum(perm_per_proc))
  }
  if (length(perm_per_proc) == 0) {
    .mmc_stop("n_perm must be >= 1; got ", n_perm, ".")
  }
  withr::with_seed(seed, {
    batch_seeds <- sample.int(10^9, length(perm_per_proc))
  })

  min_size <- max(min_size, 1)
  # abs() BEFORE any sorting: this is the step that turns the ranking into a
  # |score| ranking and is why NES sign is not a biological direction.
  stats <- abs(stats)^gsea_param

  # -- pathway members -> tie-group indices (no de-duplication) -------------
  pathways_pos <- lapply(pathways, function(p) {
    as.vector(stats::na.omit(fastmatch::fmatch(as.character(p), names(ranks))))
  })
  pathways_filtered <- lapply(pathways_pos, function(s) ranks[s])
  pathways_sizes <- vapply(pathways_filtered, length, integer(1))

  to_keep <- which(min_size <= pathways_sizes & pathways_sizes <= max_size)
  m <- length(to_keep)
  if (m == 0) return(empty)
  pathways_filtered <- pathways_filtered[to_keep]
  pathways_sizes    <- pathways_sizes[to_keep]
  K <- max(pathways_sizes)

  # -- enrichment scores ----------------------------------------------------
  # fgsea > 1.24.0 is the branch upstream takes (renv.lock pins fgsea 1.36.2, so
  # it is also the only branch this pipeline can reach): it re-sorts the already
  # absolute values descending. Kept because it defines the ranking the
  # reference implementation scores against.
  if (utils::packageVersion("fgsea") > "1.24.0") {
    stats <- sort(stats, decreasing = TRUE)
  }
  # Upstream wraps calcGseaStat in a tryCatch that falls back to
  # `list(res = 0, leadingEdge = c())`. That fallback is not decorative: because
  # tie-group indices are never de-duplicated, a pathway holding two ECs with
  # the SAME score passes a non-strictly-increasing `selectedStats`, and
  # fgsea::calcGseaStat asserts `all(head(S, -1) < tail(S, -1))` — so such a
  # pathway really does come out of the reference implementation with ES = 0,
  # NES = 0 and an empty leading edge.
  #
  # We reproduce that numerically AND record WHY each fallback happened. A
  # blanket "tied scores" label would hide any other calcGseaStat failure behind
  # a plausible-sounding explanation, so the reason is classified from the actual
  # condition (see .mmc_gsea_fallback_reason()) and anything unrecognised is
  # reported verbatim as unexpected.
  gsea_res <- lapply(pathways_filtered, function(selected) {
    if (length(selected) == 0 || any(is.na(selected))) {
      return(list(res = 0, leadingEdge = c(),
                  .mmc_reason = .mmc_gsea_fallback_reason(selected, NULL)))
    }
    tryCatch(
      fgsea::calcGseaStat(stats = stats, selectedStats = selected,
                          gseaParam = gsea_param, returnLeadingEdge = TRUE),
      error = function(e) {
        list(res = 0, leadingEdge = c(),
             .mmc_reason = .mmc_gsea_fallback_reason(selected,
                                                     conditionMessage(e)))
      })
  })
  es_defaulted <- vapply(gsea_res, function(x) !is.null(x$.mmc_reason),
                         logical(1), USE.NAMES = FALSE)
  es_reason <- vapply(gsea_res,
                      function(x) if (is.null(x$.mmc_reason)) NA_character_ else
                        x$.mmc_reason,
                      character(1), USE.NAMES = FALSE)
  unexpected <- es_defaulted & startsWith(es_reason, .MMC_GSEA_FALLBACK_UNEXPECTED)
  if (any(unexpected)) {
    warning("mummichog GSEA: ", sum(unexpected), " pathway(s) hit an ",
            "UNEXPECTED calcGseaStat failure and took the reference ",
            "implementation's ES = 0 fallback: ",
            paste(unique(es_reason[unexpected]), collapse = " | "),
            call. = FALSE)
  }
  pathway_scores <- vapply(gsea_res, function(x) as.numeric(x$res), numeric(1),
                           USE.NAMES = FALSE)
  leading_edges <- lapply(gsea_res, function(x) {
    if (length(x$leadingEdge) == 0) character(0) else names(stats)[x$leadingEdge]
  })

  # -- permutation tallies --------------------------------------------------
  tallies <- lapply(seq_along(perm_per_proc), function(i) {
    n1 <- perm_per_proc[i]
    if (m == 1) {
      # Upstream's plain sample.int() loop for a single tested pathway. Seeded
      # here so our run is reproducible; upstream leaves this path to the
      # BiocParallel worker's RNG, which is not seed-deterministic.
      acc <- list(leEs = 0, geEs = 0, leZero = 0, geZero = 0,
                  leZeroSum = 0, geZeroSum = 0)
      withr::with_seed(batch_seeds[i], {
        for (k in seq_len(n1)) {
          rand_es <- fgsea::calcGseaStat(
            stats = stats, selectedStats = sample.int(length(stats), K),
            gseaParam = 1)
          acc$leEs      <- acc$leEs + (rand_es <= pathway_scores)
          acc$geEs      <- acc$geEs + (rand_es >= pathway_scores)
          acc$leZero    <- acc$leZero + (rand_es <= 0)
          acc$geZero    <- acc$geZero + (rand_es >= 0)
          acc$leZeroSum <- acc$leZeroSum + pmin(rand_es, 0)
          acc$geZeroSum <- acc$geZeroSum + pmax(rand_es, 0)
        }
      })
      return(acc)
    }
    aux <- .mmc_gsea_perm_batch(stats, pathway_scores, pathways_sizes, n1,
                                batch_seeds[i])
    aux[c("leEs", "geEs", "leZero", "geZero", "leZeroSum", "geZeroSum")]
  })

  # Sum each tally across batches, per pathway. Identical to upstream for any
  # n_perm <= granularity (1000) — which covers the default 100 — and it is what
  # upstream's row-indexed aggregation intends; see the note in
  # run_mummichog_gsea() for the >1000 case.
  add <- function(field) {
    Reduce(`+`, lapply(tallies, function(t) as.numeric(t[[field]])))
  }
  leEs <- add("leEs"); geEs <- add("geEs")
  leZero <- add("leZero"); geZero <- add("geZero")
  leZeroSum <- add("leZeroSum"); geZeroSum <- add("geZeroSum")

  pval <- pmin((1 + leEs) / (1 + leZero), (1 + geEs) / (1 + geZero))
  le_zero_mean <- leZeroSum / leZero
  ge_zero_mean <- geZeroSum / geZero

  es  <- pathway_scores
  nes <- es / ifelse(es > 0, ge_zero_mean, abs(le_zero_mean))
  n_more_extreme <- ifelse(es > 0, geEs, leEs)

  # BH over exactly the tested pathways.
  padj <- stats::p.adjust(pval, method = "fdr")

  # Leading edge: tie-group names split back to EC ids, then intersected with
  # the pathway's own ECs (upstream's `mapply(intersect, ...)`).
  lead <- vapply(seq_len(m), function(i) {
    le <- unlist(strsplit(leading_edges[[i]], "; ", fixed = TRUE),
                 use.names = FALSE)
    pw <- names(pathways_filtered[[i]])
    hit <- unique(le[le %in% pw])
    if (length(hit) == 0) NA_character_ else paste(hit, collapse = "; ")
  }, character(1))

  data.frame(
    pathway      = names(pathways_filtered),
    pval         = as.numeric(pval),
    padj         = as.numeric(padj),
    ES           = as.numeric(es),
    NES          = as.numeric(nes),
    nMoreExtreme = as.numeric(n_more_extreme),
    size         = as.numeric(pathways_sizes),
    leadingEdge  = lead,
    es_defaulted = es_defaulted,
    es_reason    = es_reason,
    stringsAsFactors = FALSE
  )
}

# Prefix marking a fallback whose cause we do NOT recognise. Anything carrying
# it is surfaced as a warning rather than explained away.
.MMC_GSEA_FALLBACK_UNEXPECTED <- "unexpected calcGseaStat failure: "

#' Classify why the reference implementation's ES = 0 fallback fired
#'
#' Upstream's `tryCatch` swallows every `calcGseaStat` failure into the same
#' `ES = 0` result, so the reason has to be reconstructed. It is classified from
#' the CONDITION, not from a guess:
#'
#' \describe{
#'   \item{tied EC scores}{`selectedStats` holds duplicate ranked positions —
#'     the direct consequence of upstream not de-duplicating tie-group indices,
#'     and what `calcGseaStat`'s strictly-increasing assertion rejects. Detected
#'     on the indices themselves, not on the message text.}
#'   \item{every ranked position selected}{`calcGseaStat` refuses the degenerate
#'     case where the pathway covers the whole ranking.}
#'   \item{empty or missing members}{upstream's own pre-check branch, which
#'     returns the default without calling `calcGseaStat` at all.}
#'   \item{anything else}{reported verbatim behind
#'     `.MMC_GSEA_FALLBACK_UNEXPECTED`, so a genuine bug or a future fgsea change
#'     is visible instead of being mislabelled as a tie.}
#' }
#'
#' @param selected The pathway's ranked-position vector.
#' @param msg      `conditionMessage()` of the caught error, or `NULL` when the
#'   fallback came from upstream's pre-check rather than an error.
#' @return A single character scalar describing the cause.
#' @noRd
.mmc_gsea_fallback_reason <- function(selected, msg) {
  if (is.null(msg)) {
    return(if (length(selected) == 0) "pathway has no ranked members" else
      "pathway members include a missing rank")
  }
  # The tie condition IS duplicated ranked positions; check that directly.
  if (any(duplicated(selected))) {
    n <- sum(duplicated(selected))
    return(sprintf("tied EC scores (%d duplicate ranked position%s)",
                   n, if (n == 1) "" else "s"))
  }
  if (grepl("all genes are selected", msg, fixed = TRUE)) {
    return("pathway selects every ranked position")
  }
  paste0(.MMC_GSEA_FALLBACK_UNEXPECTED, msg)
}

#' Call fgsea's cumulative permutation batch the way upstream does
#'
#' `calcGseaStatCumulativeBatch()` is fgsea-internal (upstream reaches it with
#' `fgsea:::`), and its `scoreType` argument only exists from fgsea > 1.12.0 —
#' upstream branches on exactly that. Isolated here so the one internal call in
#' this file is guarded and explained in one place.
#'
#' @param stats,pathway_scores,pathways_sizes,iterations,seed Passed through.
#' @return The batch's tally list.
#' @noRd
.mmc_gsea_perm_batch <- function(stats, pathway_scores, pathways_sizes,
                                 iterations, seed) {
  fn <- tryCatch(get("calcGseaStatCumulativeBatch",
                     envir = asNamespace("fgsea")),
                 error = function(e) NULL)
  if (is.null(fn)) {
    .mmc_stop("this fgsea build does not expose calcGseaStatCumulativeBatch, ",
              "which the MetaboAnalyst-style GSEA permutation scheme requires.")
  }
  args <- list(stats = stats, gseaParam = 1,
               pathwayScores = pathway_scores,
               pathwaysSizes = pathways_sizes,
               iterations = iterations, seed = seed)
  if (utils::packageVersion("fgsea") > "1.12.0") args$scoreType <- "std"
  do.call(fn, args)
}


# ==== NES interpretation ====================================================

#' The one sanctioned description of NES sign for this analysis
#'
#' Two independent reasons NES sign must not be over-read here:
#'
#'   1. the ranked vector is transformed to |score|
#'      (`stats <- abs(stats)^gseaParam`), so it carries no direction; and
#'   2. pathway positions are built from the SIGNED-score ordering
#'      (`ranks[fmatch(members, names(ranks))]`) BEFORE that transform and the
#'      subsequent magnitude re-sort, so the indices a pathway is scored at no
#'      longer necessarily correspond to where its ECs sit in the transformed
#'      ranking at all.
#'
#' Sign is therefore retained purely for parity with the reference
#' implementation, and is deliberately NOT described as a direction — neither
#' biological up/down, nor a claim about the magnitude of the pathway members'
#' own scores. Kept as a single function so every table, plot, export and
#' report sentence says the same thing, and so the regression test has one
#' place to assert.
#'
#' @return A single character scalar.
mmc_gsea_nes_note <- function() {
  paste0("NES sign is retained to reproduce the pinned MetaboAnalystR result. ",
         "Because the reference implementation transforms and reorders the ",
         "score vector after pathway positions are constructed, NES sign ",
         "should not be interpreted as biological up/down direction or as a ",
         "direct statement about the magnitude of the pathway members' ",
         "original scores.")
}


# ==== the GSEA run ==========================================================

#' Run MetaboAnalyst-style GSEA on the mummichog EmpiricalCompound universe
#'
#' Uses the FULL ranked EC list — no feature significance cutoff — so this is a
#' genuinely different question from the ORA the pinned engine already reported.
#' The engine's own results are read-only inputs here; nothing of the ORA is
#' recomputed or overwritten.
#'
#' Defaults are MetaboAnalyst's (`n_perm = 100`, `gsea_param = 1`,
#' `min_size = 1`, `max_size = Inf`, `seed = 123`). Overriding any of them is a
#' deliberate departure from the reference implementation and is reported back
#' in `deviations`.
#'
#' @param files    One contrast's mummichog output files.
#' @param de_table That contrast's DE table (for the signed ranking statistic).
#' @param model    Model index from `read_mummichog_model_pathways()` /
#'   `mmc_load_model_pathways()`.
#' @param contrast Contrast label, carried through as provenance only — it is
#'   deliberately NOT used to interpret NES sign.
#' @param n_perm,min_size,max_size,gsea_param,seed See
#'   `mmc_gsea_metaboanalyst()`; defaults are the pinned upstream values.
#' @param rank_metric How features sharing one m/z are merged (see
#'   `mmc_ec_scores()`).
#' @return `NULL` when GSEA cannot run (fgsea unavailable, no model, no ECs, no
#'   usable statistic, no pathway passing the size filter). Otherwise a list:
#'   \describe{
#'     \item{table}{One row per tested pathway with `Pathway`,
#'       `Pathway size (model compounds)`, `Detected ECs`, `Tested size`, `ES`,
#'       `NES`, `P.Value`, `padj`, `Leading-edge EmpiricalCompounds`, sorted by
#'       ascending `P.Value`.}
#'     \item{ranks}{The signed EC score vector the ranking was built from.}
#'     \item{stats, tie_ranks}{The two vectors handed to the engine.}
#'     \item{metric, metric_label}{Which ranking statistic was chosen, and why.}
#'     \item{nes_note}{`mmc_gsea_nes_note()`.}
#'     \item{params}{The exact engine settings used.}
#'     \item{deviations}{Character vector of departures from the pinned
#'       reference defaults; empty when there are none.}
#'     \item{reference}{The pinned MetaboAnalystR repo + commit.}
#'     \item{contrast, n_ec, n_pathways}{Provenance.}
#'   }
run_mummichog_gsea <- function(files, de_table, model, contrast = NULL,
                               n_perm     = .MMC_GSEA_DEFAULTS$n_perm,
                               min_size   = .MMC_GSEA_DEFAULTS$min_size,
                               max_size   = .MMC_GSEA_DEFAULTS$max_size,
                               gsea_param = .MMC_GSEA_DEFAULTS$gsea_param,
                               seed       = .MMC_GSEA_DEFAULTS$seed,
                               rank_metric = "mean") {
  if (!requireNamespace("fgsea", quietly = TRUE)) {
    message("mummichog GSEA: fgsea not available — skipping")
    return(NULL)
  }
  if (is.null(model) || length(model$pathways) == 0) {
    message("mummichog GSEA: no metabolic model pathways available — skipping")
    return(NULL)
  }
  rank <- mmc_gsea_rank_metric(de_table)
  if (is.null(rank)) {
    message("mummichog GSEA: no usable ranking statistic in the DE table — skipping")
    return(NULL)
  }

  ec_feat <- read_mummichog_ec_features(files)
  ec_cand <- read_mummichog_ec_candidates(files)
  if (nrow(ec_feat) == 0 || nrow(ec_cand) == 0) {
    message("mummichog GSEA: no EmpiricalCompound tables among the mummichog ",
            "outputs — skipping")
    return(NULL)
  }

  ec_scores <- mmc_ec_scores(ec_feat, rank$values, rank_metric = rank_metric)
  if (length(ec_scores) == 0) {
    message("mummichog GSEA: no EmpiricalCompound could be scored — skipping")
    return(NULL)
  }
  sets <- mmc_pathway_ec_sets(model$pathways, ec_cand, names(ec_scores))
  if (length(sets) == 0) {
    message("mummichog GSEA: no pathway has a detected EmpiricalCompound — skipping")
    return(NULL)
  }
  ranked <- mmc_gsea_ranked_inputs(ec_scores)

  res <- tryCatch(
    mmc_gsea_metaboanalyst(sets, ranked$stats, ranked$ranks, n_perm = n_perm,
                           min_size = min_size, max_size = max_size,
                           gsea_param = gsea_param, seed = seed),
    error = function(e) {
      warning("mummichog GSEA: engine failed: ", conditionMessage(e),
              call. = FALSE)
      NULL
    }
  )
  if (is.null(res) || nrow(res) == 0) {
    message("mummichog GSEA: no pathway passed the size filter")
    return(NULL)
  }

  # Three different quantities, all reported rather than conflated:
  #   * model compounds  — what the pathway contains
  #   * detected ECs     — what this dataset saw in it
  #   * tested size      — the tie-group index vector the engine scored, which
  #                        can exceed detected ECs when ECs share a score
  model_size <- vapply(res$pathway,
                       function(p) as.numeric(length(model$pathways[[p]])),
                       numeric(1), USE.NAMES = FALSE)
  detected <- vapply(res$pathway,
                     function(p) as.numeric(length(sets[[p]])),
                     numeric(1), USE.NAMES = FALSE)

  tbl <- data.frame(
    check.names = FALSE, stringsAsFactors = FALSE,
    "Pathway"                          = res$pathway,
    "Pathway size (model compounds)"   = model_size,
    "Detected ECs"                     = detected,
    "Tested size"                      = res$size,
    "ES"                               = round(res$ES, 4),
    "NES"                              = round(res$NES, 4),
    "P.Value"                          = res$pval,
    "padj"                             = res$padj,
    "Leading-edge EmpiricalCompounds"  = res$leadingEdge,
    # Reported so a defaulted 0 is never read as a measured enrichment score.
    # The flag is deliberately generic and the cause lives beside it, rather
    # than every fallback being labelled a tie.
    "ES defaulted by reference implementation" = res$es_defaulted,
    "ES fallback reason"                       = res$es_reason
  )
  tbl <- tbl[order(tbl[["P.Value"]], na.last = TRUE), , drop = FALSE]

  # Any departure from the pinned reference defaults is recorded, not hidden.
  deviations <- character(0)
  d <- .MMC_GSEA_DEFAULTS
  if (!identical(as.numeric(n_perm), as.numeric(d$n_perm))) {
    deviations <- c(deviations, sprintf(
      "n_perm = %s (MetaboAnalyst default %s)", n_perm, d$n_perm))
  }
  if (!identical(as.numeric(min_size), as.numeric(d$min_size))) {
    deviations <- c(deviations, sprintf(
      "min_size = %s (MetaboAnalyst default %s)", min_size, d$min_size))
  }
  if (!identical(as.numeric(max_size), as.numeric(d$max_size))) {
    deviations <- c(deviations, sprintf(
      "max_size = %s (MetaboAnalyst default Inf)", max_size))
  }
  if (!identical(as.numeric(gsea_param), as.numeric(d$gsea_param))) {
    deviations <- c(deviations, sprintf(
      "gsea_param = %s (MetaboAnalyst default %s)", gsea_param, d$gsea_param))
  }
  if (!identical(as.numeric(seed), as.numeric(d$seed))) {
    deviations <- c(deviations, sprintf(
      "seed = %s (MetaboAnalyst default %s)", seed, d$seed))
  }
  # Upstream aggregates its permutation tallies by data.table ROW, which is only
  # well defined for a single batch; we sum per pathway across batches instead.
  if (n_perm > .MMC_GSEA_GRANULARITY) {
    deviations <- c(deviations, sprintf(
      paste0("n_perm = %s exceeds upstream's batch granularity (%s); ",
             "permutation tallies are summed per pathway across batches, ",
             "which upstream's row-indexed aggregation does not do"),
      n_perm, .MMC_GSEA_GRANULARITY))
  }

  n_defaulted <- sum(res$es_defaulted)
  if (n_defaulted > 0) {
    reasons <- table(res$es_reason[res$es_defaulted])
    message("mummichog GSEA: ", n_defaulted, "/", nrow(res), " pathway(s) took ",
            "the reference implementation's ES = 0 fallback (",
            paste(sprintf("%s x%d", names(reasons), as.integer(reasons)),
                  collapse = "; "),
            "); flagged in the results table with the reason.")
  }
  message("mummichog GSEA: ", nrow(tbl), " pathways over ", length(ec_scores),
          " EmpiricalCompounds (", length(ranked$stats),
          " ranked positions), ranked by ", rank$label)

  list(
    table        = tbl,
    ranks        = ec_scores,
    stats        = ranked$stats,
    tie_ranks    = ranked$ranks,
    metric       = rank$metric,
    metric_label = rank$label,
    nes_note     = mmc_gsea_nes_note(),
    params       = list(n_perm = n_perm, min_size = min_size,
                        max_size = max_size, gsea_param = gsea_param,
                        seed = seed, rank_metric = rank_metric,
                        fgsea_version = as.character(
                          utils::packageVersion("fgsea"))),
    deviations   = deviations,
    reference    = list(repo = .MMC_GSEA_REF_REPO,
                        commit = .MMC_GSEA_REF_COMMIT),
    contrast     = contrast,
    n_ec         = length(ec_scores),
    n_positions  = length(ranked$stats),
    n_pathways   = nrow(tbl),
    n_es_defaulted = n_defaulted,
    es_fallback_reasons = if (n_defaulted == 0) character(0) else
      sort(unique(res$es_reason[res$es_defaulted]))
  )
}


# ==== plot ==================================================================

#' MetaboAnalyst-style GSEA summary scatter for peaks-to-pathways
#'
#' Reproduces the encoding of the pinned
#' `peaks_to_function.R::PlotPeaks2Paths()` GSEA branch:
#'
#' \itemize{
#'   \item x = `NES`
#'   \item y = `-log10(raw GSEA p-value)`
#'   \item colour = `NES` on a diverging scale centred at 0, in MetaboAnalyst's
#'     own colours (`#458B00` -> `#fffee0` -> `#7f0000`)
#'   \item point size = `sqrt(-log10(p))`, which is literally what MetaboAnalyst
#'     computes there (`radi.vec <- sqrt(abs(y))`, with `y` the -log10 p already
#'     on the vertical axis). It is therefore a redundant re-encoding of
#'     significance and carries no additional quantity — the legend says exactly
#'     that instead of inventing a meaning, and never exposes the upstream
#'     variable name.
#'   \item the most significant pathways labelled with `ggrepel`
#' }
#'
#' NES sign is kept only for parity with the reference implementation and is not
#' an interpretable direction — see `mmc_gsea_nes_note()`.
#'
#' Two additions to the reference, both non-encoding: the points are drawn as
#' outlined circles (`shape = 21`) so the near-white middle of the diverging
#' scale stays visible — matching the outlined bubbles used elsewhere in this
#' report — and the NES = 0 / p-cutoff guides are drawn, as in the other pathway
#' plots in this pipeline.
#'
#' @param gsea_df  The `table` from `run_mummichog_gsea()` (needs `Pathway`,
#'   `NES`, `P.Value`).
#' @param title    Plot title.
#' @param subtitle Plot subtitle (e.g. the contrast). Optional.
#' @param p_cutoff Significance cutoff for the dashed reference line.
#' @param label_top Number of most-significant pathways to label (needs
#'   `ggrepel`; silently unlabelled when it is unavailable).
#' @return A ggplot object, or `NULL` when there is nothing to plot (so the
#'   report section hides gracefully).
plot_mummichog_gsea_scatter <- function(gsea_df, title, subtitle = NULL,
                                        p_cutoff = 0.05, label_top = 8) {
  if (is.null(gsea_df) || !is.data.frame(gsea_df) || nrow(gsea_df) == 0) {
    return(NULL)
  }
  if (!all(c("Pathway", "NES", "P.Value") %in% names(gsea_df))) return(NULL)

  df <- data.frame(
    pathway = as.character(gsea_df$Pathway),
    NES     = suppressWarnings(as.numeric(gsea_df$NES)),
    p       = suppressWarnings(as.numeric(gsea_df[["P.Value"]])),
    stringsAsFactors = FALSE
  )
  df <- df[is.finite(df$NES) & is.finite(df$p), , drop = FALSE]
  if (nrow(df) == 0) return(NULL)

  # -log10 with a floor so an exact-zero p can't blow up the axis.
  df$neg_log10_p <- -log10(pmax(df$p, .Machine$double.eps))
  # MetaboAnalyst's radi.vec, verbatim: sqrt of the -log10 p on the y axis.
  df$significance_size <- sqrt(df$neg_log10_p)

  lim <- max(abs(df$NES), na.rm = TRUE)

  p <- ggplot2::ggplot(df, ggplot2::aes(x = .data$NES, y = .data$neg_log10_p)) +
    ggplot2::geom_vline(xintercept = 0, colour = "grey80") +
    ggplot2::geom_hline(yintercept = -log10(p_cutoff),
                        linetype = "dashed", colour = "grey50") +
    ggplot2::annotate("text", x = Inf, y = -log10(p_cutoff),
                      label = sprintf("p = %g", p_cutoff),
                      hjust = 1.05, vjust = -0.5, size = 3, colour = "grey40") +
    ggplot2::geom_point(
      ggplot2::aes(size = .data$significance_size, fill = .data$NES),
      shape = 21, colour = "grey25", stroke = 0.4, alpha = 0.9) +
    ggplot2::scale_fill_gradient2(
      low = "#458B00", mid = "#fffee0", high = "#7f0000", midpoint = 0,
      limits = c(-lim, lim), name = "NES") +
    # ASCII legend text on purpose: this label is rendered by the graphics
    # device on PNG/PDF export, where a non-ASCII glyph warns and degrades on a
    # minimal font setup.
    ggplot2::scale_size_continuous(
      range = c(1, 5), name = "Significance\nsqrt(-log10 p)") +
    ggplot2::labs(
      title    = title,
      subtitle = subtitle,
      x        = "NES  (normalized enrichment score)",
      y        = "-log10(GSEA p-value)") +
    ggplot2::theme_minimal() +
    ggplot2::theme(
      plot.title    = ggplot2::element_text(face = "bold", hjust = 0.5),
      plot.subtitle = ggplot2::element_text(hjust = 0.5))

  # Label the most significant pathways. ggrepel is optional across the repo, so
  # guard it and simply skip labels when it is not installed.
  if (label_top > 0 && requireNamespace("ggrepel", quietly = TRUE)) {
    lab_df <- df[order(df$p), , drop = FALSE]
    lab_df <- lab_df[seq_len(min(label_top, nrow(lab_df))), , drop = FALSE]
    p <- p + ggrepel::geom_text_repel(
      data = lab_df,
      ggplot2::aes(label = .data$pathway),
      size = 3, max.overlaps = Inf, box.padding = 0.5,
      min.segment.length = 0, seed = 42)
  }
  p
}
